"""The ``openui`` dialect: golden parses, the malformed set, and streaming truncation.

No DB, no network. The dialect fixtures live in ``tests/fixtures/dsl/*.openui`` and
their expected IR in ``tests/fixtures/ui-specs/*.json`` — the same JSON files the
frontend renders (§12.3), so a contract break fails both sides at once.
"""

from __future__ import annotations

import json
import pathlib

import pytest

from src.render import UI_KIT, RenderError, RenderParseError, UISpec, get_render_backend
from src.render.backends import openui as openui_module
from src.render.backends.openui import (
    MAX_NESTING_DEPTH,
    OpenUiLangBackend,
    infer_format,
)

BACKEND = OpenUiLangBackend()

_DSL_DIR = pathlib.Path(__file__).parent / "fixtures" / "dsl"
_SPEC_DIR = pathlib.Path(__file__).parent / "fixtures" / "ui-specs"

VALID = (
    "explanation_basic",
    "explanation_callout_first",
    "mixed_quiz",
    "exercise_only",
    "chart_data",
    "table_nested",
    "card_nested",
    "escapes",
    "deep_stack",
    "quiz_types",
    "inline_nested",
)

# One fixture per failure mode. The first three are the three frozen grammar rules
# of §5.4, in order.
MALFORMED = (
    "malformed_unescaped_quote",  # rule 1
    "malformed_flat_table_rows",  # rule 2
    "malformed_literal_newline",  # rule 3
    "malformed_unclosed_array",
    "malformed_missing_assign",
    "invalid_unknown_component",
)


def _dsl(name: str) -> str:
    return (_DSL_DIR / f"{name}.openui").read_text(encoding="utf-8")


def _golden(name: str) -> dict:
    return json.loads((_SPEC_DIR / f"{name}.json").read_text(encoding="utf-8"))


def test_there_are_at_least_eight_valid_dialects_and_six_malformed() -> None:
    assert len(VALID) >= 8
    assert len(MALFORMED) == 6
    assert len(set(VALID) | set(MALFORMED)) == len(VALID) + len(MALFORMED)


def test_the_fixture_directory_holds_exactly_the_declared_corpus() -> None:
    """Both suites and the frontend read this directory; a stray file must be loud."""
    on_disk = {path.stem for path in _DSL_DIR.glob("*.openui")}
    assert on_disk == set(VALID) | set(MALFORMED)


# -- valid dialects -----------------------------------------------------------------


@pytest.mark.parametrize("name", VALID)
def test_parse_matches_the_golden_spec(name: str) -> None:
    spec = BACKEND.parse(_dsl(name))
    assert spec.model_dump(mode="json") == _golden(name)


@pytest.mark.parametrize("name", VALID)
def test_every_golden_is_a_valid_ui_spec(name: str) -> None:
    spec = UISpec.model_validate(_golden(name))
    assert spec.version == "skillnet-ui/1"
    assert spec.component(spec.root) is not None


def test_escapes_decode_to_real_characters() -> None:
    spec = BACKEND.parse(_dsl("escapes"))
    intro = spec.component("intro")
    cita = spec.component("cita")
    assert intro is not None and cita is not None
    assert '"' in intro.props["text"]
    assert "\\" in intro.props["text"]
    assert "\n" in cita.props["text"]
    # Rule 3: the literal source carries no line break inside the quotes.
    assert len(_dsl("escapes").rstrip("\n").split("\n")) == 3


def test_code_block_keeps_its_newlines_as_escapes() -> None:
    spec = BACKEND.parse(_dsl("card_nested"))
    codigo = spec.component("codigo")
    assert codigo is not None
    assert codigo.props["code"].count("\n") == 2


def test_nested_table_rows_are_a_matrix() -> None:
    spec = BACKEND.parse(_dsl("table_nested"))
    tabla = spec.component("tabla")
    assert tabla is not None
    assert tabla.props["rows"] == [
        ["Tienda", "30 dias", "0 EUR"],
        ["Web", "14 dias", "3,95 EUR"],
        ["Telefono", "14 dias", "0 EUR"],
    ]


def test_numbers_keep_their_type_and_sign() -> None:
    spec = BACKEND.parse(_dsl("chart_data"))
    grafico = spec.component("grafico")
    assert grafico is not None
    assert grafico.props["values"] == [12, 8.5, -3]


def test_forward_references_and_loose_whitespace_are_accepted() -> None:
    spec = BACKEND.parse(_dsl("deep_stack"))
    assert spec.root == "root"
    assert spec.component("grupo") is not None


def test_code_fences_and_blank_lines_are_ignored() -> None:
    raw = _dsl("quiz_types")
    assert raw.lstrip().startswith("```")
    assert "\n\n" in raw
    assert len(BACKEND.parse(raw).components) == 5


def test_root_is_the_component_nobody_references() -> None:
    spec = BACKEND.parse(
        'contenedor = Stack([intro], "md")\n'
        'intro = TextContent("Para que te sirve: cobrar bien.", "lead")\n'
    )
    assert spec.root == "contenedor"


def test_empty_arrays_are_legal() -> None:
    spec = BACKEND.parse(_dsl("exercise_only"))
    q1 = spec.component("q1")
    assert q1 is not None
    assert q1.props["options"] == []


# -- inline sub-components (the standard's form, accepted since 2026-07-27) ----------
#
# The prompt this repository serves is generated by `library.prompt()` and says
# «Sub-components can be inline or referenced; prefer references for better streaming».
# Refusing the inline form was our bug: measured against qwen2.5:7b-instruct it cost the
# whole repair loop, because the parse error blamed a quote for a parenthesis.

_INLINE = 'root = Stack([TextContent("Hola.", "lead")], "md")\n'
_REFERENCED = 'root = Stack([intro], "md")\nintro = TextContent("Hola.", "lead")\n'


def test_a_simple_inline_child_is_flattened_with_a_synthetic_id() -> None:
    spec = BACKEND.parse(_INLINE)
    assert [c.id for c in spec.components] == ["root", "root_1"]
    assert spec.root == "root"
    inline = spec.component("root_1")
    assert inline is not None
    assert inline.type == "TextContent"
    assert inline.props == {"text": "Hola.", "variant": "lead"}
    assert spec.components[0].children == ["root_1"]


def test_the_inline_and_the_referenced_form_are_the_same_screen() -> None:
    """Only the ids differ: the same components, the same tree, the same format."""
    inline = BACKEND.parse(_INLINE)
    referenced = BACKEND.parse(_REFERENCED)
    assert inline.format == referenced.format
    assert [c.type for c in inline.components] == [c.type for c in referenced.components]
    assert [c.props for c in inline.components] == [c.props for c in referenced.components]


def test_inline_and_referenced_children_mix_in_one_array() -> None:
    raw = (
        'root = Stack([TextContent("Hola.", "lead"), pasos], "md")\n'
        'pasos = StepSequence("Proceso", ["Uno", "Dos"])\n'
    )
    spec = BACKEND.parse(raw)
    assert spec.components[0].children == ["root_1", "pasos"]
    assert [c.id for c in spec.components] == ["root", "root_1", "pasos"]


def test_an_inline_child_of_a_card_is_flattened_too() -> None:
    raw = (
        'root = Stack([intro, ficha], "md")\n'
        'intro = TextContent("Hola.", "lead")\n'
        'ficha = Card("Ficha", [TextContent("Dentro de la ficha.", "body")])\n'
    )
    spec = BACKEND.parse(raw)
    ficha = spec.component("ficha")
    assert ficha is not None
    assert ficha.children == ["ficha_1"]
    nested = spec.component("ficha_1")
    assert nested is not None
    assert nested.props["text"] == "Dentro de la ficha."


def test_an_inline_call_inside_an_inline_call_keeps_the_ownership_in_its_id() -> None:
    raw = (
        'root = Stack([intro, Card("Ficha", [TextContent("Dentro.", "body")])], "md")\n'
        'intro = TextContent("Hola.", "lead")\n'
    )
    spec = BACKEND.parse(raw)
    assert [c.id for c in spec.components] == ["root", "root_1", "root_1_1", "intro"]
    card = spec.component("root_1")
    assert card is not None
    assert card.children == ["root_1_1"]


def test_the_synthetic_ids_are_deterministic_across_parses() -> None:
    """Round trips and cache keys compare specs across runs, so the ids cannot drift."""
    raw = _dsl("inline_nested")
    first = BACKEND.parse(raw)
    for _ in range(5):
        assert BACKEND.parse(raw).model_dump(mode="json") == first.model_dump(mode="json")


def test_a_synthetic_id_never_steals_one_the_program_declares() -> None:
    """`root_1` is taken by a real declaration three lines down, so the inline gets `root_2`."""
    raw = (
        'root = Stack([TextContent("Hola.", "lead"), root_1], "md")\n'
        'root_1 = TextContent("Declarado a mano.", "body")\n'
    )
    spec = BACKEND.parse(raw)
    assert spec.components[0].children == ["root_2", "root_1"]
    declared = spec.component("root_1")
    assert declared is not None
    assert declared.props["text"] == "Declarado a mano."


def test_serialize_writes_the_referenced_form_and_reparsing_it_changes_nothing() -> None:
    """`serialize` has one canonical output, and it is the flat one their prompt prefers."""
    spec = BACKEND.parse(_INLINE)
    program = BACKEND.serialize(spec)
    assert program == 'root = Stack([root_1], "md")\nroot_1 = TextContent("Hola.", "lead")\n'
    assert "TextContent(" not in program.split("\n")[0]
    assert BACKEND.parse(program) == spec
    assert BACKEND.serialize(BACKEND.parse(program)) == program


def test_rule_4_counts_the_components_after_flattening() -> None:
    """Ten inline blocks cost exactly what ten declared ones cost."""
    cards = ", ".join(
        f'Card("C{n}", [TextContent("uno", "body"), TextContent("dos", "body")])'
        for n in range(4)
    )
    raw = f'root = Stack([TextContent("Hola.", "lead"), {cards}], "md")\n'
    with pytest.raises(RenderParseError) as excinfo:
        BACKEND.parse(raw)
    assert any("at most 12 components" in error for error in excinfo.value.errors)
    assert "got 14" in str(excinfo.value)


def test_rule_4_counts_the_root_fan_out_after_flattening() -> None:
    children = ", ".join(
        f'TextContent("linea {n}", "{"lead" if n == 0 else "body"}")' for n in range(6)
    )
    raw = f'root = Stack([{children}], "md")\n'
    with pytest.raises(RenderParseError) as excinfo:
        BACKEND.parse(raw)
    assert "at most 5" in str(excinfo.value)


def test_an_inline_call_outside_a_children_array_is_named_as_such() -> None:
    raw = 'root = Stack([a], "md")\na = TextContent(Callout("info", "Ojo."), "lead")\n'
    with pytest.raises(RenderParseError) as excinfo:
        BACKEND.parse(raw)
    message = str(excinfo.value)
    assert "does not take a component" in message
    assert "children array" in message
    assert "id = Componente(...)" in message


def test_nesting_deeper_than_the_cap_is_a_message_and_not_a_recursion_error() -> None:
    """A hostile line must not be able to pick the CPython recursion limit as its DoS."""
    depth = MAX_NESTING_DEPTH * 4
    raw = "root = " + "Stack([" * depth + '], "md")' * depth + "\n"
    with pytest.raises(RenderParseError) as excinfo:
        BACKEND.parse(raw)
    assert f"deeper than {MAX_NESTING_DEPTH} levels" in str(excinfo.value)


def test_a_pathological_nesting_never_reaches_the_interpreter_limit() -> None:
    raw = "root = " + "Stack([" * 5000 + '], "md")' * 5000 + "\n"
    with pytest.raises(RenderParseError):
        BACKEND.parse(raw)
    assert BACKEND.parse_partial(raw).components == []


# -- format recovery ----------------------------------------------------------------


@pytest.mark.parametrize(
    ("name", "expected"),
    (
        ("explanation_basic", "explanation"),
        ("mixed_quiz", "mixed"),
        ("exercise_only", "exercise"),
        ("chart_data", "chart"),
    ),
)
def test_format_is_inferred_from_the_component_mix(name: str, expected: str) -> None:
    assert BACKEND.parse(_dsl(name)).format == expected
    assert infer_format(BACKEND.parse(_dsl(name)).components) == expected


def test_an_explicit_format_wins_over_inference() -> None:
    # What the runtime does: decide_formato already chose, so it is passed in.
    spec = BACKEND.parse(_dsl("chart_data"), ui_format="mixed")
    assert spec.format == "mixed"


def test_an_explicit_format_still_enforces_rule_7() -> None:
    raw = 'root = Stack([a], "md")\na = TextContent("Sin lead.", "body")\n'
    with pytest.raises(RenderParseError) as excinfo:
        BACKEND.parse(raw, ui_format="explanation")
    assert any("rule 7" in e for e in excinfo.value.errors)


# -- malformed dialects -------------------------------------------------------------


@pytest.mark.parametrize("name", MALFORMED)
def test_malformed_dialect_raises_render_parse_error(name: str) -> None:
    with pytest.raises(RenderParseError):
        BACKEND.parse(_dsl(name))


@pytest.mark.parametrize("name", MALFORMED)
def test_the_error_carries_the_messages_the_repair_prompt_needs(name: str) -> None:
    with pytest.raises(RenderParseError) as excinfo:
        BACKEND.parse(_dsl(name))
    assert excinfo.value.errors
    assert all(isinstance(message, str) and message for message in excinfo.value.errors)


def test_grammar_rule_1_unescaped_quote() -> None:
    with pytest.raises(RenderParseError) as excinfo:
        BACKEND.parse(_dsl("malformed_unescaped_quote"))
    assert "line 2" in str(excinfo.value)
    assert 'written \\"' in str(excinfo.value)


def test_grammar_rule_1_an_escaped_quote_is_fine() -> None:
    raw = 'root = Stack([a], "md")\na = TextContent("Dijo \\"hola\\" ayer.", "lead")\n'
    component = BACKEND.parse(raw).component("a")
    assert component is not None
    assert component.props["text"] == 'Dijo "hola" ayer.'


def test_grammar_rule_2_table_rows_must_be_nested() -> None:
    with pytest.raises(RenderParseError) as excinfo:
        BACKEND.parse(_dsl("malformed_flat_table_rows"))
    assert "array of arrays" in str(excinfo.value)


def test_grammar_rule_3_a_literal_newline_breaks_the_string() -> None:
    with pytest.raises(RenderParseError) as excinfo:
        BACKEND.parse(_dsl("malformed_literal_newline"))
    assert "unterminated text value" in str(excinfo.value)


def test_grammar_rule_3_the_escape_form_is_accepted() -> None:
    raw = 'root = Stack([a], "md")\na = TextContent("Uno.\\nDos.", "lead")\n'
    component = BACKEND.parse(raw).component("a")
    assert component is not None
    assert component.props["text"] == "Uno.\nDos."


def test_wrong_arity_is_rejected() -> None:
    with pytest.raises(RenderParseError) as excinfo:
        BACKEND.parse('root = Stack([a])\na = TextContent("Hola.", "lead")\n')
    assert "positional arguments" in str(excinfo.value)


def test_quoted_child_ids_are_rejected() -> None:
    with pytest.raises(RenderParseError) as excinfo:
        BACKEND.parse('root = Stack(["a"], "md")\na = TextContent("Hola.", "lead")\n')
    assert "array of component ids" in str(excinfo.value)


def test_an_invalid_escape_is_rejected() -> None:
    with pytest.raises(RenderParseError) as excinfo:
        BACKEND.parse('root = Stack([a], "md")\na = TextContent("Tab\\there.", "lead")\n')
    assert "invalid escape" in str(excinfo.value)


def test_trailing_text_after_the_call_is_rejected() -> None:
    with pytest.raises(RenderParseError) as excinfo:
        BACKEND.parse('root = Stack([a], "md") y algo mas\n')
    assert "trailing text" in str(excinfo.value)


def test_the_model_cannot_emit_markdown() -> None:
    with pytest.raises(RenderParseError) as excinfo:
        BACKEND.parse('root = Stack([m], "md")\nm = Markdown("# Hola")\n')
    assert "unknown component 'Markdown'" in str(excinfo.value)


def test_an_empty_program_is_rejected() -> None:
    with pytest.raises(RenderParseError):
        BACKEND.parse("```openui\n```\n")


# -- the error messages are the contract with the model, not prose for a human --------
#
# The repair loop re-injects them verbatim, so a message that GUESSES a cause makes the
# model rewrite code that was already correct. Measured: an inline component call used to
# be reported as «expected ',' or ']', found '('; the usual cause is an unescaped double
# quote», and the loop never converged. Each of these pins a message against its cause.


def test_a_named_argument_is_named_as_a_named_argument() -> None:
    raw = 'root = Stack(children = [intro], gap = "md")\nintro = TextContent("H.", "lead")\n'
    with pytest.raises(RenderParseError) as excinfo:
        BACKEND.parse(raw)
    message = str(excinfo.value)
    assert "no named arguments" in message
    assert 'Stack([intro], "md")' in message  # what to write instead
    # And it does not send the model looking for a quote to escape.
    assert "\\\"" not in message


def test_a_split_declaration_is_reported_as_a_split_declaration() -> None:
    raw = 'root = Stack([intro],\n    "md")\nintro = TextContent("H.", "lead")\n'
    with pytest.raises(RenderParseError) as excinfo:
        BACKEND.parse(raw)
    message = str(excinfo.value)
    assert "line 1" in message
    assert "never continues on the next line" in message


def test_a_continuation_line_says_so_instead_of_repeating_the_grammar() -> None:
    raw = 'root = Stack([intro], "md")\nintro = TextContent("H.", "lead")\n    "body")\n'
    with pytest.raises(RenderParseError) as excinfo:
        BACKEND.parse(raw)
    message = str(excinfo.value)
    assert "line 3" in message
    assert "continues the previous one" in message
    assert "on ONE line" in message


def test_the_quote_diagnosis_only_fires_when_a_text_value_really_just_closed() -> None:
    with pytest.raises(RenderParseError) as excinfo:
        BACKEND.parse(_dsl("malformed_unescaped_quote"))
    assert "the text ended at the double quote before it" in str(excinfo.value)
    # The construction that used to get this message now parses.
    assert BACKEND.parse(_INLINE).component("root_1") is not None


def test_no_parser_message_guesses_a_cause_it_did_not_check() -> None:
    """The phrasing that broke the repair loop must not come back in any message."""
    source = pathlib.Path(openui_module.__file__ or "").read_text(encoding="utf-8")
    assert "the usual cause" not in source


def test_a_missing_open_parenthesis_says_a_declaration_is_a_call() -> None:
    with pytest.raises(RenderParseError) as excinfo:
        BACKEND.parse("root = Stack\n")
    assert "every declaration is a call" in str(excinfo.value)


def test_a_trailing_comma_is_rejected() -> None:
    with pytest.raises(RenderParseError) as excinfo:
        BACKEND.parse('root = Stack([a,], "md")\na = TextContent("Hola.", "lead")\n')
    assert "trailing comma" in str(excinfo.value)


# -- parse_partial: streaming --------------------------------------------------------

_SWEEP_FIXTURES = ("explanation_basic", "escapes", "mixed_quiz")
_SWEEP = [
    (name, cut)
    for name in _SWEEP_FIXTURES
    for cut in range(len(_dsl(name)) + 1)
]
_FULL_IDS = {name: [c.id for c in BACKEND.parse(_dsl(name)).components] for name in _SWEEP_FIXTURES}


@pytest.mark.parametrize(("name", "cut"), _SWEEP)
def test_parse_partial_never_raises_at_any_truncation(name: str, cut: int) -> None:
    """Every byte offset of a stream, not a random sample (and no new dependency)."""
    prefix = _dsl(name)[:cut]
    spec = BACKEND.parse_partial(prefix)
    assert isinstance(spec, UISpec)
    assert spec.version == "skillnet-ui/1"
    ids = [component.id for component in spec.components]
    assert len(ids) == len(set(ids))
    # One component per line in these fixtures, so a completed line is a completed
    # component and nothing beyond the last newline may leak in.
    assert ids == _FULL_IDS[name][: prefix.count("\n")]


def test_parse_partial_drops_the_half_written_last_line() -> None:
    raw = _dsl("explanation_basic")
    cut = raw.index("\n") + 1 + 20  # first line plus 20 bytes of the second
    spec = BACKEND.parse_partial(raw[:cut])
    assert [c.id for c in spec.components] == ["root"]


def test_parse_partial_keeps_a_complete_last_line() -> None:
    raw = _dsl("explanation_basic")
    cut = raw.index("\n") + 1
    assert len(BACKEND.parse_partial(raw[:cut]).components) == 1


def test_parse_partial_tolerates_dangling_forward_references() -> None:
    spec = BACKEND.parse_partial('root = Stack([intro, quiz], "md")\n')
    assert spec.components[0].children == ["intro", "quiz"]
    assert spec.root == "root"


def test_parse_partial_on_empty_input_is_an_empty_spec() -> None:
    spec = BACKEND.parse_partial("")
    assert spec.components == []
    assert spec.root == ""


@pytest.mark.parametrize("name", MALFORMED)
def test_parse_partial_never_raises_on_malformed_input(name: str) -> None:
    spec = BACKEND.parse_partial(_dsl(name))
    assert isinstance(spec, UISpec)


def test_parse_partial_skips_the_broken_line_and_keeps_the_rest() -> None:
    raw = (
        'root = Stack([a, b], "md")\n'
        'a = TextContent("roto porque falta la coma" "lead")\n'
        'b = TextContent("Este si vale.", "body")\n'
    )
    ids = [c.id for c in BACKEND.parse_partial(raw).components]
    assert ids == ["root", "b"]


def test_parse_partial_yields_every_component_of_a_completed_inline_line() -> None:
    spec = BACKEND.parse_partial(_INLINE)
    assert [c.id for c in spec.components] == ["root", "root_1"]


@pytest.mark.parametrize("cut", range(len(_dsl("inline_nested")) + 1))
def test_parse_partial_never_raises_on_half_written_nesting(cut: int) -> None:
    """Every byte offset of the inline fixture, including mid-call and mid-array."""
    spec = BACKEND.parse_partial(_dsl("inline_nested")[:cut])
    assert isinstance(spec, UISpec)
    ids = [component.id for component in spec.components]
    assert len(ids) == len(set(ids))


@pytest.mark.parametrize(
    "prefix",
    (
        'root = Stack([TextContent("Hola.",',
        'root = Stack([TextContent("Hola.", "lead")',
        'root = Stack([TextContent("Hola.",\n',
        'root = Stack([Card("F", [TextContent("x",\n',
    ),
)
def test_parse_partial_drops_a_line_whose_nesting_is_still_open(prefix: str) -> None:
    assert BACKEND.parse_partial(prefix).components == []


def test_parse_partial_lets_a_retransmitted_line_win() -> None:
    raw = (
        'root = Stack([a], "md")\n'
        'a = TextContent("Primera version.", "lead")\n'
        'a = TextContent("Segunda version.", "lead")\n'
    )
    spec = BACKEND.parse_partial(raw)
    component = spec.component("a")
    assert component is not None
    assert component.props["text"] == "Segunda version."
    assert len(spec.components) == 2


# -- the registry -------------------------------------------------------------------


def test_the_default_backend_is_openui() -> None:
    assert get_render_backend().name == "openui"
    assert get_render_backend("openui") is get_render_backend()


def test_an_unknown_backend_is_a_render_error() -> None:
    with pytest.raises(RenderError):
        get_render_backend("a2tl")


def test_the_parser_accepts_exactly_the_nine_emittable_components() -> None:
    """What ``GRAMMAR``'s ``comp_name`` production used to assert, asserted on behaviour.

    The EBNF is no longer a constant (the prompt comes from ``library.prompt()`` now), so
    the closed catalogue is checked where it is enforced: in ``parse``.
    """
    accepted = set()
    for name in (*UI_KIT.names, "Timeline", "SandboxHTML"):
        try:
            BACKEND.parse(f'root = {name}()\n')
        except RenderParseError as exc:
            if "unknown component" in str(exc):
                continue
            accepted.add(name)  # rejected for arity/props, so the name itself is known
    assert accepted == {
        "Stack",
        "TextContent",
        "Card",
        "Callout",
        "StepSequence",
        "Table",
        "CodeBlock",
        "Chart",
        "QuizItem",
    }
