"""The SkillNet UI Kit — the frozen catalogue of §5.3, validator side.

This module is the source of truth for **validation**: the component list, the exact
prop names, the value types, the closed enums and the *positional* order the OpenUI
dialect uses. ``src/render/spec.py`` enforces all of it, and the OpenUI parser cannot:
``compileSchema()`` keeps only ``{name, required, defaultValue}``, so their parser checks
arity and presence and nothing else.

Since 2026-07-26 the prompt itself is generated by ``library.prompt()`` from the
frontend kit (``apps/skillnet-web/src/components/courses/kit/``), and since this rewrite
this module no longer *retypes* that catalogue by hand either: for every component the
frontend advertises to the model, the name/props/description come straight from
``openui_catalog.json`` (the same artefact ``src/render/prompt.py`` reads), loaded once at
import time by :func:`_load_llm_components`. There is exactly one authored catalogue —
the frontend kit — and this module derives its half of the validator from it, so a prop
renamed, reordered or retyped there arrives here automatically the next time the artefact
is regenerated; ``tests/test_render_prompt_artifact.py`` still exists, but only to catch a
stale or hand-tampered artefact, not to compare two independent declarations.

The artefact cannot carry everything a ``ComponentSpec`` needs, because it is written for
the model prompt, not for Python: it says nothing about which block is a *container*,
which function it competes for (``ContentFunction``/``FunctionFit``), or which components
exist for the backend only and never reach the frontend prompt catalogue at all
(``Markdown`` — server-authored fallback; ``DidactActivity`` — legacy, playback-only;
``PodcastPlayer``/``InfographicImage``/``SourceImage`` — broker-scoped, injected
per-node). That metadata is genuinely backend business, so it stays declared here, in
:data:`_BACKEND_METADATA`
(keyed by name, for the JSON-derived components) and in :data:`_BACKEND_ONLY_COMPONENTS`
(full hand-written specs, for the five components the artefact does not describe at all).

Two closed lists are imported instead of retyped, so they cannot drift either:
``ExerciseType`` (the six ``item_type`` values, §5.3) and ``BLOOM_LEVELS`` (the six
values the ``node_attempts.bloom_level`` CHECK accepts, §3.4).
"""

from __future__ import annotations

import enum
import json
from dataclasses import dataclass
from pathlib import Path

from src.models.exercise import ExerciseType
from src.models.node_attempt import BLOOM_LEVELS

GAP_VALUES: tuple[str, ...] = ("sm", "md", "lg")
TEXT_VARIANTS: tuple[str, ...] = ("body", "lead", "caption")
CALLOUT_TONES: tuple[str, ...] = ("info", "warn", "success")
CHART_KINDS: tuple[str, ...] = ("bar", "line")
VOICE_STYLES: tuple[str, ...] = ("neutral", "warm", "formal")
ITEM_TYPES: tuple[str, ...] = tuple(m.value for m in ExerciseType)

#: The ``variant`` a ``TextContent`` must carry to satisfy contract rule 7 (§5.2).
LEAD_VARIANT = "lead"


class PropKind(str, enum.Enum):
    """The value shapes the dialect can express."""

    STRING = "string"
    NUMBER = "number"
    ENUM = "enum"
    STRING_LIST = "string[]"
    STRING_MATRIX = "string[][]"
    NUMBER_LIST = "number[]"
    #: Array of component ids. Maps to ``Component.children``, never to ``props``.
    REFS = "ref[]"


class ContentFunction(str, enum.Enum):
    """What a piece of source material *does*, independent of which block renders it.

    The layer `docs/design/arquitectura-componentes-funcional.md` introduces: a detector
    says "this enumerates", not "use a Table". The mapping to blocks lives in the
    components themselves (``ComponentSpec.functions``), so adding a component becomes a
    local edit instead of teaching ``shape.py`` one more name.

    Only ENUMERAR, PROCEDIMENTAR and CUANTIFICAR are reachable today: they are what the
    four detectors of ``shape.py`` emit. The rest are declared so components can already
    claim them, but nothing routes there until a detector or a classifier does (phases 3
    and 4). A function no detector emits is dead weight in the registry, not a bug.
    """

    ENUMERAR = "enumerar"
    PROCEDIMENTAR = "procedimentar"
    CUANTIFICAR = "cuantificar"
    CONTRASTAR = "contrastar"
    VARIAR = "variar"
    EXPLORAR = "explorar"
    LOCALIZAR = "localizar"
    EVALUAR = "evaluar"


@dataclass(frozen=True, slots=True)
class FunctionFit:
    """A component's claim on one function, and how strongly it wants it.

    ``rank`` breaks ties, lower first. It belongs to the *pair* and not to the component
    because a block can be the obvious answer for one function and the fallback for
    another: ``Table`` is the default for ENUMERAR and a poor second for CONTRASTAR.
    """

    function: ContentFunction
    rank: int = 50


@dataclass(frozen=True, slots=True)
class PropSpec:
    name: str
    kind: PropKind
    description: str
    choices: tuple[str, ...] = ()

    @property
    def signature(self) -> str:
        """How the prop is advertised in the prompt fragment."""
        if self.kind is PropKind.ENUM:
            return f"{self.name}: " + "|".join(f'"{c}"' for c in self.choices)
        if self.kind is PropKind.REFS:
            return f"{self.name}: [id, ...]"
        return f"{self.name}: {self.kind.value}"


@dataclass(frozen=True, slots=True)
class ComponentSpec:
    name: str
    purpose: str
    props: tuple[PropSpec, ...]
    #: ``root`` must be a container (contract rule 1, §5.2).
    is_container: bool = False
    #: ``Markdown`` is reachable from ``fallback_seed`` only; the LLM cannot emit it.
    llm_emittable: bool = True
    #: A **broker-scoped** content component: the LLM may emit it, but ONLY when the media
    #: broker injects it into the episode scope because a READY media artefact of that kind
    #: exists for the node (and the learner preference allows it). It is a real, validated
    #: component of the kit — the validator accepts it like any other — but it is kept OUT
    #: of the frozen frontend catalogue/drift digest (``llm_components``), because the
    #: generator never sees it in the general closed scope, only through the broker's
    #: grounded, per-node whitelist addendum. This is what lets ``kit.py`` carry the
    #: signature without regenerating the frontend prompt artefact.
    broker_scoped: bool = False
    #: Historical programs may still contain a retired authoring symbol. It remains
    #: parseable for playback without returning to the prompt catalogue.
    legacy_parseable: bool = False
    #: The functions this component competes for. Empty = it is never proposed by the
    #: function layer and can only arrive by an explicit rule in a prompt.
    functions: tuple[FunctionFit, ...] = ()

    @property
    def prop_names(self) -> tuple[str, ...]:
        return tuple(p.name for p in self.props)

    @property
    def children_prop(self) -> PropSpec | None:
        for prop in self.props:
            if prop.kind is PropKind.REFS:
                return prop
        return None

    @property
    def value_props(self) -> tuple[PropSpec, ...]:
        """Props that live in ``Component.props`` (everything but the refs array)."""
        return tuple(p for p in self.props if p.kind is not PropKind.REFS)

    def prop(self, name: str) -> PropSpec | None:
        for prop in self.props:
            if prop.name == name:
                return prop
        return None

    @property
    def signature(self) -> str:
        """``Chart(kind: "bar"|"line", title: string, ...)`` — used by the prompt."""
        return f"{self.name}(" + ", ".join(p.signature for p in self.props) + ")"


@dataclass(frozen=True, slots=True)
class UIKit:
    components: tuple[ComponentSpec, ...]

    def get(self, name: str) -> ComponentSpec | None:
        for component in self.components:
            if component.name == name:
                return component
        return None

    @property
    def names(self) -> tuple[str, ...]:
        return tuple(c.name for c in self.components)

    @property
    def llm_components(self) -> tuple[ComponentSpec, ...]:
        """The components advertised in the frozen frontend catalogue/prompt.

        Excludes broker-scoped components: those are real, validate-able components the LLM
        may emit, but only when the media broker whitelists them per-node, so they must not
        enter the general catalogue (and must not shift its drift digest).
        """
        return tuple(
            c for c in self.components if c.llm_emittable and not c.broker_scoped
        )

    @property
    def broker_components(self) -> tuple[ComponentSpec, ...]:
        """Broker-scoped content components, injected per-node when a ready artefact exists."""
        return tuple(c for c in self.components if c.broker_scoped)

    @property
    def llm_names(self) -> tuple[str, ...]:
        return tuple(c.name for c in self.llm_components)

    @property
    def container_names(self) -> tuple[str, ...]:
        return tuple(c.name for c in self.components if c.is_container)

    def candidates_for(self, function: ContentFunction) -> tuple[str, ...]:
        """Components that claim ``function``, best first.

        The registry lookup that replaces the block name hard-coded in ``shape.py``.
        Ties break on catalogue order, so the result is deterministic and a component
        added at the end never displaces an incumbent by accident.
        """
        claims = [
            (fit.rank, index, component.name)
            for index, component in enumerate(self.components)
            for fit in component.functions
            if fit.function is function and component.llm_emittable
        ]
        return tuple(name for _, _, name in sorted(claims))

    def primary_for(self, function: ContentFunction) -> str:
        """The component a function resolves to when nobody declines. ``""`` if none."""
        candidates = self.candidates_for(function)
        return candidates[0] if candidates else ""


# --------------------------------------------------------------------------------------
# Backend-only metadata for the components the frontend artefact *does* describe: the
# name, its props and its description are read from ``openui_catalog.json`` below, and
# this dict adds only what a validation-side ``ComponentSpec`` needs and the prompt
# artefact has no reason to carry (containment, and which content function it competes
# for). A name with no entry here gets the ``ComponentSpec`` defaults (not a container,
# no function claim) — that is every component below except the two listed.
# --------------------------------------------------------------------------------------

_BACKEND_METADATA: dict[str, dict[str, object]] = {
    "Stack": {"is_container": True},
    "Card": {
        "is_container": True,
        "functions": (FunctionFit(ContentFunction.ENUMERAR, 60), FunctionFit(ContentFunction.VARIAR, 40)),
    },
    "Callout": {"functions": (FunctionFit(ContentFunction.CONTRASTAR, 70),)},
    "StepSequence": {"functions": (FunctionFit(ContentFunction.PROCEDIMENTAR, 10),)},
    "Table": {
        "functions": (
            FunctionFit(ContentFunction.ENUMERAR, 10),
            FunctionFit(ContentFunction.CUANTIFICAR, 10),
            FunctionFit(ContentFunction.CONTRASTAR, 60),
        ),
    },
    "Chart": {"functions": (FunctionFit(ContentFunction.CUANTIFICAR, 20),)},
    "QuizItem": {"functions": (FunctionFit(ContentFunction.EVALUAR, 10),)},
    "BeforeAfter": {"functions": (FunctionFit(ContentFunction.CONTRASTAR, 10),)},
    "DragOrder": {"functions": (FunctionFit(ContentFunction.EVALUAR, 20),)},
    "Flashcard": {"functions": (FunctionFit(ContentFunction.EXPLORAR, 20),)},
    "HintReveal": {"functions": (FunctionFit(ContentFunction.EXPLORAR, 30),)},
    "DidactGlossary": {"functions": (FunctionFit(ContentFunction.EXPLORAR, 35),)},
    "DidactTimeline": {"functions": (FunctionFit(ContentFunction.PROCEDIMENTAR, 20),)},
    "DidactWorkedExample": {
        "functions": (FunctionFit(ContentFunction.PROCEDIMENTAR, 25), FunctionFit(ContentFunction.EXPLORAR, 25)),
    },
    "LearningExperience": {"functions": (FunctionFit(ContentFunction.EXPLORAR, 5),)},
}

#: Components the frontend prompt artefact does not describe at all — either because the
#: model may never emit them (``Markdown``, ``DidactActivity``) or because they are
#: broker-scoped (injected per-node outside the general catalogue, §5.3). These stay fully
#: hand-declared; there is nothing to derive them from.
_BACKEND_ONLY_COMPONENTS: tuple[ComponentSpec, ...] = (
    ComponentSpec(
        name="Markdown",
        purpose="Solo para fallback_seed; el modelo no puede emitirlo",
        llm_emittable=False,
        props=(PropSpec("content", PropKind.STRING, "Contenido de la leccion semilla"),),
    ),
    ComponentSpec(
        name="PodcastPlayer",
        broker_scoped=True,
        purpose=(
            "Reproductor del podcast (audio overview) ya generado para este nodo. "
            "Referencia un artefacto de audio real por id; nunca inventes el id. "
            "Solo esta disponible cuando el broker lo ofrece"
        ),
        props=(
            PropSpec("artifact_id", PropKind.STRING, "Id del MediaArtifact de podcast (kind=podcast, status=done)"),
            PropSpec("title", PropKind.STRING, "Titulo breve que se muestra sobre el reproductor"),
        ),
    ),
    ComponentSpec(
        name="InfographicImage",
        broker_scoped=True,
        purpose=(
            "Imagen de la infografia ya generada para este nodo. Referencia un artefacto "
            "de imagen real por id; nunca inventes el id. Solo esta disponible cuando el "
            "broker lo ofrece"
        ),
        props=(
            PropSpec("artifact_id", PropKind.STRING, "Id del MediaArtifact de infografia (kind=infographic, status=done)"),
            PropSpec("alt", PropKind.STRING, "Texto alternativo accesible que describe la imagen"),
        ),
    ),
    ComponentSpec(
        name="SourceImage",
        broker_scoped=True,
        purpose=(
            "Imagen que ya venia DENTRO del documento de origen de este curso (una "
            "captura de pantalla, un diagrama, una foto real). No es material generado: "
            "es el material del cliente, y por eso se muestra con su procedencia. "
            "Referencia una imagen real por id; nunca inventes el id. Solo esta "
            "disponible cuando el broker la ofrece"
        ),
        props=(
            PropSpec("image_id", PropKind.STRING, "Id de la fila source_images ofrecida por el broker"),
            PropSpec("alt", PropKind.STRING, "Texto alternativo accesible que describe la imagen"),
            PropSpec(
                "caption",
                PropKind.STRING,
                "Procedencia que se imprime bajo la imagen (documento > seccion, pag. N)",
            ),
            # LAST on purpose, and the frontend depends on it being last: the asset route
            # is document-scoped, so the client needs both ids to fetch the bytes — but if
            # a program ever arrives with only the first three, positional mapping still
            # lands image_id/alt/caption correctly and the missing document_id degrades
            # into a handled "unavailable" state instead of painting the caption as alt.
            PropSpec("document_id", PropKind.STRING, "Id del documento que contiene la imagen"),
        ),
    ),
    ComponentSpec(
        name="DidactActivity",
        llm_emittable=False,
        legacy_parseable=True,
        functions=(FunctionFit(ContentFunction.EVALUAR, 10), FunctionFit(ContentFunction.EXPLORAR, 10)),
        purpose="Actividad Didact revisada, cargada por id desde SkillNet; nunca contiene respuestas en el programa",
        props=(
            PropSpec("activity_id", PropKind.STRING, "Id opaco de una ActivityDefinition revisada"),
            PropSpec("component_id", PropKind.STRING, "Id didact.* elegido por el planificador"),
        ),
    ),
)

#: Where ``PronunciationExercise`` and ``AudioExplanation`` sit relative to the
#: JSON-derived block: the §5.3 table order interleaves the artefact's components with
#: the backend-only ones, so the known names are assembled name-by-name in this fixed
#: order. A component the artefact advertises that is NOT in this tuple (i.e. added on
#: the frontend after this tuple was last touched) is not dropped: :func:`_build_ui_kit`
#: appends it at the end, in the artefact's own order, with the ``ComponentSpec``
#: defaults (``is_container=False``, no function claim) — the same defaults every
#: component below with no ``_BACKEND_METADATA`` entry already gets. That default is
#: correct for the overwhelming majority of new components (leaf content blocks); a
#: genuinely new *container* or one that should compete for a ``ContentFunction`` still
#: needs a `_BACKEND_METADATA` entry added by hand, but nothing about *discovering* the
#: component requires touching this module first.
_CATALOGUE_ORDER: tuple[str, ...] = (
    "Stack", "TextContent", "Card", "Callout", "StepSequence", "Table", "CodeBlock",
    "Chart", "QuizItem", "BeforeAfter", "Markdown", "DragOrder", "AudioExplanation",
    "PodcastPlayer", "InfographicImage", "SourceImage", "PronunciationExercise", "Flashcard",
    "HintReveal", "DidactGlossary", "DidactTimeline", "DidactWorkedExample",
    "LearningExperience", "DidactActivity",
)

_HERE = Path(__file__).parent
_CATALOG_ARTIFACT_PATH = _HERE / "openui_catalog.json"

#: How to fix every error this module raises while loading the artefact.
_REGENERATE_HINT = (
    "regenerate the artefacts: cd apps/skillnet-web && "
    "node scripts/generate-openui-prompt.mjs"
)


def _load_catalog_artifact() -> dict[str, object]:
    try:
        raw = _CATALOG_ARTIFACT_PATH.read_text(encoding="utf-8")
    except OSError as exc:
        raise RuntimeError(
            f"missing render artefact {_CATALOG_ARTIFACT_PATH.name}: {_REGENERATE_HINT}"
        ) from exc
    try:
        return json.loads(raw)
    except json.JSONDecodeError as exc:
        raise RuntimeError(
            f"{_CATALOG_ARTIFACT_PATH.name} is not valid JSON: {_REGENERATE_HINT}"
        ) from exc


def _prop_from_artifact(raw: dict[str, object]) -> PropSpec:
    return PropSpec(
        name=str(raw["name"]),
        kind=PropKind(raw["kind"]),
        description="",
        choices=tuple(str(choice) for choice in (raw.get("choices") or ())),  # type: ignore[union-attr]
    )


def _component_from_artifact(raw: dict[str, object]) -> ComponentSpec:
    name = str(raw["name"])
    metadata = _BACKEND_METADATA.get(name, {})
    props = raw["props"]
    assert isinstance(props, list)
    return ComponentSpec(
        name=name,
        purpose=str(raw.get("description") or ""),
        props=tuple(_prop_from_artifact(prop) for prop in props),
        is_container=bool(metadata.get("is_container", False)),
        functions=tuple(metadata.get("functions", ())),  # type: ignore[arg-type]
    )


def _build_ui_kit() -> UIKit:
    """Assemble ``UI_KIT`` from ``openui_catalog.json`` plus the backend-only metadata.

    The two sources are keyed by component name and merged in :data:`_CATALOGUE_ORDER`
    (the fixed §5.3 table order), so a component's position among ties in
    :meth:`UIKit.candidates_for` cannot shift just because the artefact happened to list
    it differently.
    """
    artifact = _load_catalog_artifact()
    from_artifact = {
        str(component["name"]): _component_from_artifact(component)  # type: ignore[arg-type]
        for component in artifact["prompt_components"]  # type: ignore[union-attr]
    }
    backend_only = {component.name: component for component in _BACKEND_ONLY_COMPONENTS}

    missing = [name for name in _CATALOGUE_ORDER if name not in from_artifact and name not in backend_only]
    if missing:
        raise RuntimeError(
            f"catalogue order names {missing} that neither the artefact nor "
            f"_BACKEND_ONLY_COMPONENTS declares: {_REGENERATE_HINT}"
        )

    # Names the artefact advertises but `_CATALOGUE_ORDER` predates: appended at the end,
    # in the artefact's own order, so a component added on the frontend surfaces here
    # automatically instead of being silently dropped (see the comment on the tuple).
    discovered = [name for name in from_artifact if name not in _CATALOGUE_ORDER]

    order = (*_CATALOGUE_ORDER, *discovered)
    return UIKit(
        components=tuple(from_artifact.get(name) or backend_only[name] for name in order)
    )


UI_KIT = _build_ui_kit()

COMPONENT_NAMES: tuple[str, ...] = UI_KIT.names
LLM_COMPONENT_NAMES: tuple[str, ...] = UI_KIT.llm_names
CONTAINER_NAMES: tuple[str, ...] = UI_KIT.container_names

__all__ = [
    "BLOOM_LEVELS",
    "CALLOUT_TONES",
    "CHART_KINDS",
    "COMPONENT_NAMES",
    "CONTAINER_NAMES",
    "GAP_VALUES",
    "ITEM_TYPES",
    "LEAD_VARIANT",
    "LLM_COMPONENT_NAMES",
    "TEXT_VARIANTS",
    "UI_KIT",
    "VOICE_STYLES",
    "ComponentSpec",
    "PropKind",
    "PropSpec",
    "UIKit",
]
