// One-off helper used to populate src/content/docs/en/*.md from
// docs/design/*.md and RUNNING.md. Not part of the build — run manually
// after editing source docs in ../../docs/design, then re-run `npm run
// build` to verify.
//
// This only refreshes the ENGLISH copy (en/). The Spanish translations in
// src/content/docs/es/*.md are written by hand and are NOT regenerated by
// this script — after running it, check the console output below for which
// es/ files are now behind their en/ counterpart (by mtime) and translate
// them manually.
import { readFileSync, writeFileSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..", "..");
const destDir = join(here, "..", "src", "content", "docs", "en");
const esDir = join(here, "..", "src", "content", "docs", "es");

const entries = [
  { slug: "quickstart", title: "Arranque rápido", titleEn: "Quickstart", order: 1, section: "start", src: join(repoRoot, "RUNNING.md") },
  { slug: "architecture", title: "Arquitectura", titleEn: "Architecture", order: 2, section: "core", src: join(repoRoot, "docs/design/architecture.md") },
  { slug: "backend-api", title: "API backend", titleEn: "Backend API", order: 3, section: "core", src: join(repoRoot, "docs/design/backend-api.md") },
  { slug: "data-model", title: "Modelo de datos", titleEn: "Data model", order: 4, section: "core", src: join(repoRoot, "docs/design/data-model.md") },
  { slug: "content-generation", title: "Generación de contenido", titleEn: "Content generation", order: 5, section: "core", src: join(repoRoot, "docs/design/content-generation.md") },
  { slug: "chat-agents", title: "Chat y agentes", titleEn: "Chat and agents", order: 6, section: "core", src: join(repoRoot, "docs/design/chat-agents.md") },
  { slug: "llm-integration", title: "Integración LLM", titleEn: "LLM integration", order: 7, section: "core", src: join(repoRoot, "docs/design/llm-integration.md") },
  { slug: "rag-retrieval", title: "RAG y recuperación", titleEn: "RAG and retrieval", order: 8, section: "core", src: join(repoRoot, "docs/design/rag-retrieval.md") },
  { slug: "security", title: "Seguridad", titleEn: "Security", order: 9, section: "core", src: join(repoRoot, "docs/design/security.md") },
  { slug: "background-processing", title: "Procesos en segundo plano", titleEn: "Background processing", order: 10, section: "core", src: join(repoRoot, "docs/design/background-processing.md") },
  { slug: "dynamic-courses", title: "Cursos dinámicos (v2)", titleEn: "Dynamic courses (v2)", order: 11, section: "v2", src: join(repoRoot, "docs/design/v2-dynamic-courses.md") },
  { slug: "course-scope", title: "Alcance de v1", titleEn: "v1 scope", order: 12, section: "v2", src: join(repoRoot, "docs/design/v1-scope.md") },
  { slug: "personalization", title: "Personalización", titleEn: "Personalization", order: 13, section: "extensibility", src: join(repoRoot, "docs/design/personalization.md") },
  { slug: "media-artifacts", title: "Artefactos multimedia", titleEn: "Media artifacts", order: 14, section: "extensibility", src: join(repoRoot, "docs/design/media-artifacts.md") },
  { slug: "extensibility", title: "Extensibilidad (MCP/A2A)", titleEn: "Extensibility (MCP/A2A)", order: 15, section: "extensibility", src: join(repoRoot, "docs/design/extensibility.md") },
  { slug: "design-system", title: "Sistema de diseño", titleEn: "Design system", order: 16, section: "extensibility", src: join(repoRoot, "docs/design/design-system.md") },
  { slug: "ai-course-design", title: "Diseño de cursos con IA", titleEn: "AI course design", order: 17, section: "extensibility", src: join(repoRoot, "docs/design/ai-course-design.md") },
  { slug: "audience-modes", title: "Modos de audiencia", titleEn: "Audience modes", order: 18, section: "extensibility", src: join(repoRoot, "docs/design/audience-modes.md") },
  { slug: "admin-library-talent", title: "Biblioteca y talento (admin)", titleEn: "Library and talent (admin)", order: 19, section: "extensibility", src: join(repoRoot, "docs/design/admin-library-and-talent.md") },
];

function escapeYaml(s) {
  return s.replace(/"/g, '\\"');
}

const stale = [];

for (const e of entries) {
  const body = readFileSync(e.src, "utf8");
  const frontmatter = `---\ntitle: "${escapeYaml(e.titleEn)}"\norder: ${e.order}\nsection: "${e.section}"\n---\n\n`;
  const enPath = join(destDir, `${e.slug}.md`);
  writeFileSync(enPath, frontmatter + body, "utf8");

  const esPath = join(esDir, `${e.slug}.md`);
  try {
    const esMtime = statSync(esPath).mtimeMs;
    const enMtime = statSync(enPath).mtimeMs;
    if (enMtime > esMtime) stale.push(e.slug);
  } catch {
    stale.push(e.slug); // es/ file missing entirely
  }
}

console.log(`Copied ${entries.length} docs into ${destDir}`);
if (stale.length > 0) {
  console.log(
    `\nThe following es/ translations are now older than their en/ source and need a manual re-translation:\n` +
      stale.map((slug) => `  - src/content/docs/es/${slug}.md`).join("\n"),
  );
} else {
  console.log("All es/ translations are up to date (by mtime).");
}
