"""Data access for ``node_renders`` — the shared render cache (§3.4, §9.3).

**The one rule that carries the whole cost model:** the cache lookup is
``WHERE cache_key = :key AND status = 'ready' AND NOT is_preview``. There is no
``user_id`` in the table and there must be none in the ``WHERE``, ever. Put one in either
and the hit rate is 0, which is the pillar the cost projection of §9.3 stands on.

Two consequences that read as bugs until you know why:

* ``is_preview`` rows are persisted and excluded. A preview generated by an admin
  **before** the schema was validated must never be served to an employee of the same
  bucket — that is the back door §11.3 closes.
* ``generated_by`` is nullable and set to ``NULL`` on user deletion, so removing the
  employee who happened to generate first does not destroy the render everyone else is
  reading (and the evidence behind their certificates).
"""

from __future__ import annotations

import uuid
from collections.abc import Sequence
from datetime import datetime, timezone

from sqlalchemy import select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from src.models import NodeRender, NodeRenderStatus, UiFormat
from src.repositories.base import BaseRepository

#: Statuses that mean "there is something to show". The ``ck_node_renders_served_provenance``
#: check constraint requires ``dialect``/``catalog_version``/``library_version`` on exactly
#: these two.
SERVABLE_STATUSES: tuple[NodeRenderStatus, ...] = (
    NodeRenderStatus.READY,
    NodeRenderStatus.FALLBACK,
)


class NodeRenderRepository(BaseRepository[NodeRender]):
    def __init__(self, session: AsyncSession) -> None:
        super().__init__(session, NodeRender)

    async def get_by_cache_key(self, cache_key: str) -> NodeRender | None:
        """Any row for this key, whatever its status. ``UNIQUE (cache_key)`` -> at most one."""
        query = select(NodeRender).where(NodeRender.cache_key == cache_key)
        return (await self.session.execute(query)).scalar_one_or_none()

    async def find_cached(self, cache_key: str) -> NodeRender | None:
        """The cache hit of §9.3 level 1. Never filtered by user, by design."""
        query = select(NodeRender).where(
            NodeRender.cache_key == cache_key,
            NodeRender.status == NodeRenderStatus.READY,
            NodeRender.is_preview.is_(False),
        )
        return (await self.session.execute(query)).scalar_one_or_none()

    async def get_scoped(
        self, render_id: uuid.UUID, org_id: uuid.UUID
    ) -> NodeRender | None:
        render = await self.get_by_id(render_id)
        if render is None or render.org_id != org_id:
            return None
        return render

    async def claim(
        self,
        *,
        org_id: uuid.UUID,
        node_id: uuid.UUID,
        cache_key: str,
        backend: str,
        model: str,
        tier: str,
        ui_format: object,
        generated_by: uuid.UUID | None = None,
        is_preview: bool = False,
    ) -> NodeRender:
        """Reserve the row this request will write into, as ``status='generating'``.

        Reusing a stale row of the same key rather than inserting a second one is not an
        optimisation: ``cache_key`` is ``UNIQUE`` globally, so a failed attempt would
        otherwise permanently poison its own key. A row that is already ``ready`` is
        returned untouched — the caller checked the cache first, and overwriting a served
        render would rewrite what other learners are looking at.
        """
        existing = await self.get_by_cache_key(cache_key)
        if existing is not None:
            if existing.status in SERVABLE_STATUSES:
                return existing
            existing.status = NodeRenderStatus.GENERATING
            existing.error_message = None
            existing.backend = backend
            existing.model = model
            existing.tier = tier
            existing.ui_format = _ui_format(ui_format)
            existing.is_preview = is_preview
            if generated_by is not None:
                existing.generated_by = generated_by
            await self.session.flush()
            return existing

        try:
            return await self.create(
                org_id=org_id,
                node_id=node_id,
                cache_key=cache_key,
                backend=backend,
                model=model,
                tier=tier,
                ui_format=_ui_format(ui_format),
                generated_by=generated_by,
                is_preview=is_preview,
                status=NodeRenderStatus.GENERATING,
            )
        except IntegrityError:
            # Another worker claimed the same key between the SELECT and the INSERT.
            # Losing that race is normal, not exceptional: adopt their row.
            await self.session.rollback()
            adopted = await self.get_by_cache_key(cache_key)
            if adopted is None:  # pragma: no cover - the unique index says otherwise
                raise
            return adopted

    async def mark_ready(
        self,
        render: NodeRender,
        *,
        ui_format: object,
        ui_spec: dict,
        answer_key: dict,
        dialect: str,
        catalog_version: str,
        library_version: str,
        model: str,
        tier: str,
        tokens_in: int | None = None,
        tokens_out: int | None = None,
        duration_ms: int | None = None,
        status: NodeRenderStatus = NodeRenderStatus.READY,
    ) -> NodeRender:
        """Write the finished render. ``status`` is ``ready`` or ``fallback`` (§4.2)."""
        render.ui_format = _ui_format(ui_format)
        render.ui_spec = ui_spec
        render.answer_key = answer_key
        render.dialect = dialect
        render.catalog_version = catalog_version
        render.library_version = library_version
        render.model = model
        render.tier = tier
        render.tokens_in = tokens_in
        render.tokens_out = tokens_out
        render.duration_ms = duration_ms
        render.status = status
        render.error_message = None
        await self.session.flush()
        return render

    async def release(self, render: NodeRender, reason: str) -> NodeRender:
        """Return a claimed row to ``pending``: nothing was generated and nothing failed.

        Used when the gate skips a mastered node. Leaving the row in ``generating`` would
        park its ``cache_key`` in a state that reads like a crashed worker, and marking it
        ``failed`` would report a failure for the cheapest, most desirable outcome there is.
        """
        render.status = NodeRenderStatus.PENDING
        render.error_message = reason[:2000]
        await self.session.flush()
        return render

    async def mark_failed(self, render: NodeRender, message: str) -> NodeRender:
        render.status = NodeRenderStatus.FAILED
        render.error_message = message[:2000]
        await self.session.flush()
        return render

    async def fail_by_id(self, render_id: uuid.UUID, message: str) -> NodeRender | None:
        """``mark_failed`` by id, for the error wrapper (which only has the id)."""
        render = await self.get_by_id(render_id)
        if render is None:
            return None
        return await self.mark_failed(render, message)

    async def history_for_node(
        self,
        *,
        node_id: uuid.UUID,
        render_ids: Sequence[uuid.UUID],
    ) -> Sequence[NodeRender]:
        """The renders **this learner has seen** on this node, newest first (§5.5).

        ``render_ids`` comes from ``node_render_views``: the table has no ``user_id``, so
        "the previous version" can only mean "a version I was served", never "any version
        anybody in my bucket ever got".
        """
        if not render_ids:
            return []
        query = (
            select(NodeRender)
            .where(
                NodeRender.node_id == node_id,
                NodeRender.id.in_(list(render_ids)),
                NodeRender.status.in_(list(SERVABLE_STATUSES)),
            )
            .order_by(NodeRender.created_at.desc())
        )
        return (await self.session.execute(query)).scalars().all()

    async def stale_generating(
        self, *, older_than: datetime
    ) -> Sequence[NodeRender]:
        """Rows stuck in ``generating`` (a worker died mid-render). Used by ops, not by
        the request path — a stuck row blocks its own ``cache_key`` forever."""
        query = select(NodeRender).where(
            NodeRender.status == NodeRenderStatus.GENERATING,
            NodeRender.created_at < older_than,
        )
        return (await self.session.execute(query)).scalars().all()


def _ui_format(value: object) -> UiFormat:
    """Coerce a plain string into the enum; unknown values become ``explanation``."""
    if isinstance(value, UiFormat):
        return value
    try:
        return UiFormat(str(value))
    except ValueError:
        return UiFormat.EXPLANATION


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


__all__ = ["SERVABLE_STATUSES", "NodeRenderRepository", "utcnow"]
