/* eslint-disable */
// Generated by scripts/generate-didact-registry.mjs from the pinned neutral snapshot.
// Do not edit by hand. This is installed availability, never an OpenUI shortlist.
import type { DidactRegistryEntry } from './registry-types'

export const DIDACT_REGISTRY_SOURCE = {
  "repository": "https://github.com/JoseEstevez520/Didact",
  "commit": "06c80e8a8af4f20ad20ba345b7b6b13e1cc27e0c",
  "contentSha256": "06e149348ca17501f9a5dd8decdcc51d0642898b7ff65840a3610b0cd48bff01",
  "operationalSchemaVersion": 1,
  "authoritativeTypeCount": 34
} as const

export const DIDACT_COMPONENT_REGISTRY = [
  {
    "componentId": "didact.flashcard",
    "manifestId": "didact.flashcard",
    "exportName": "Flashcard",
    "registryItem": "flashcard",
    "maturity": "stable",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "Flashcard",
      "registryItem": "flashcard",
      "sourceModule": "flashcard"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "Flashcard"
    },
    "operations": {
      "rendererMode": "direct",
      "rendererSymbol": "Flashcard",
      "emission": "enabled",
      "requiredPorts": [],
      "authoringStrategy": "inline"
    }
  },
  {
    "componentId": "didact.matching",
    "manifestId": "didact.matching-exercises",
    "exportName": "MatchingExercise",
    "registryItem": "matching-exercises",
    "maturity": "stable",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "MatchingExercise",
      "registryItem": "matching-exercises",
      "sourceModule": "matching-exercises"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "MatchingExercise"
    },
    "operations": {
      "rendererMode": "activity_definition",
      "rendererSymbol": "DidactActivity",
      "emission": "enabled",
      "requiredPorts": [
        "evaluation"
      ],
      "authoringStrategy": "server_activity"
    }
  },
  {
    "componentId": "didact.sort",
    "manifestId": "didact.matching-exercises",
    "exportName": "SortExercise",
    "registryItem": "matching-exercises",
    "maturity": "stable",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "SortExercise",
      "registryItem": "matching-exercises",
      "sourceModule": "matching-exercises"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "SortExercise"
    },
    "operations": {
      "rendererMode": "activity_definition",
      "rendererSymbol": "DidactActivity",
      "emission": "enabled",
      "requiredPorts": [
        "evaluation"
      ],
      "authoringStrategy": "server_activity"
    }
  },
  {
    "componentId": "didact.categorize",
    "manifestId": "didact.matching-exercises",
    "exportName": "CategorizeExercise",
    "registryItem": "matching-exercises",
    "maturity": "stable",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "CategorizeExercise",
      "registryItem": "matching-exercises",
      "sourceModule": "matching-exercises"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "CategorizeExercise"
    },
    "operations": {
      "rendererMode": "activity_definition",
      "rendererSymbol": "DidactActivity",
      "emission": "enabled",
      "requiredPorts": [
        "evaluation"
      ],
      "authoringStrategy": "server_activity"
    }
  },
  {
    "componentId": "didact.quiz.single-choice",
    "manifestId": "didact.quiz",
    "exportName": "SingleChoiceQuiz",
    "registryItem": "quiz-item",
    "maturity": "stable",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "SingleChoiceQuiz",
      "registryItem": "quiz-item",
      "sourceModule": "quiz-item"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "SingleChoiceQuiz"
    },
    "operations": {
      "rendererMode": "activity_definition",
      "rendererSymbol": "DidactActivity",
      "emission": "enabled",
      "requiredPorts": [
        "evaluation"
      ],
      "authoringStrategy": "server_activity"
    }
  },
  {
    "componentId": "didact.quiz.multi-select",
    "manifestId": "didact.quiz",
    "exportName": "MultiSelectQuiz",
    "registryItem": "quiz-item",
    "maturity": "stable",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "MultiSelectQuiz",
      "registryItem": "quiz-item",
      "sourceModule": "quiz-item"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "MultiSelectQuiz"
    },
    "operations": {
      "rendererMode": "activity_definition",
      "rendererSymbol": "DidactActivity",
      "emission": "enabled",
      "requiredPorts": [
        "evaluation"
      ],
      "authoringStrategy": "server_activity"
    }
  },
  {
    "componentId": "didact.quiz.true-false",
    "manifestId": "didact.quiz",
    "exportName": "TrueFalseQuiz",
    "registryItem": "quiz-item",
    "maturity": "stable",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "TrueFalseQuiz",
      "registryItem": "quiz-item",
      "sourceModule": "quiz-item"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "TrueFalseQuiz"
    },
    "operations": {
      "rendererMode": "activity_definition",
      "rendererSymbol": "DidactActivity",
      "emission": "enabled",
      "requiredPorts": [
        "evaluation"
      ],
      "authoringStrategy": "server_activity"
    }
  },
  {
    "componentId": "didact.quiz.fill-in-the-blank",
    "manifestId": "didact.quiz",
    "exportName": "FillInTheBlankQuiz",
    "registryItem": "quiz-item",
    "maturity": "stable",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "FillInTheBlankQuiz",
      "registryItem": "quiz-item",
      "sourceModule": "quiz-item"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "FillInTheBlankQuiz"
    },
    "operations": {
      "rendererMode": "activity_definition",
      "rendererSymbol": "DidactActivity",
      "emission": "enabled",
      "requiredPorts": [
        "evaluation"
      ],
      "authoringStrategy": "server_activity"
    }
  },
  {
    "componentId": "didact.quiz.short-answer",
    "manifestId": "didact.quiz",
    "exportName": "ShortAnswerQuiz",
    "registryItem": "quiz-item",
    "maturity": "stable",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "ShortAnswerQuiz",
      "registryItem": "quiz-item",
      "sourceModule": "quiz-item"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "ShortAnswerQuiz"
    },
    "operations": {
      "rendererMode": "activity_definition",
      "rendererSymbol": "DidactActivity",
      "emission": "enabled",
      "requiredPorts": [
        "evaluation"
      ],
      "authoringStrategy": "server_activity"
    }
  },
  {
    "componentId": "didact.glossary-term",
    "manifestId": "didact.glossary",
    "exportName": "Glossary",
    "registryItem": "glossary",
    "maturity": "stable",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "Glossary",
      "registryItem": "glossary",
      "sourceModule": "glossary"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "Glossary"
    },
    "operations": {
      "rendererMode": "direct",
      "rendererSymbol": "DidactGlossary",
      "emission": "enabled",
      "requiredPorts": [],
      "authoringStrategy": "inline"
    }
  },
  {
    "componentId": "didact.hint-reveal",
    "manifestId": "didact.hint-reveal",
    "exportName": "HintReveal",
    "registryItem": "hint-reveal",
    "maturity": "stable",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "HintReveal",
      "registryItem": "hint-reveal",
      "sourceModule": "hint-reveal"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "HintReveal"
    },
    "operations": {
      "rendererMode": "direct",
      "rendererSymbol": "HintReveal",
      "emission": "enabled",
      "requiredPorts": [],
      "authoringStrategy": "inline"
    }
  },
  {
    "componentId": "didact.progress",
    "manifestId": "didact.progress",
    "exportName": "ProgressIndicator",
    "registryItem": "progress-indicators",
    "maturity": "stable",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "ProgressIndicator",
      "registryItem": "progress-indicators",
      "sourceModule": "progress-indicator"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "ProgressIndicator"
    },
    "operations": {
      "rendererMode": "activity_definition",
      "rendererSymbol": "DidactActivity",
      "emission": "enabled",
      "requiredPorts": [
        "progress"
      ],
      "authoringStrategy": "server_activity"
    }
  },
  {
    "componentId": "didact.mastery-badge",
    "manifestId": "didact.mastery-badge",
    "exportName": "MasteryBadge",
    "registryItem": "mastery-badge",
    "maturity": "stable",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "MasteryBadge",
      "registryItem": "mastery-badge",
      "sourceModule": "mastery-badge"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "MasteryBadge"
    },
    "operations": {
      "rendererMode": "activity_definition",
      "rendererSymbol": "DidactActivity",
      "emission": "enabled",
      "requiredPorts": [
        "progress"
      ],
      "authoringStrategy": "server_activity"
    }
  },
  {
    "componentId": "didact.rubric",
    "manifestId": "didact.rubric",
    "exportName": "Rubric",
    "registryItem": "rubric",
    "maturity": "stable",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "Rubric",
      "registryItem": "rubric",
      "sourceModule": "rubric"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "Rubric"
    },
    "operations": {
      "rendererMode": "activity_definition",
      "rendererSymbol": "DidactActivity",
      "emission": "enabled",
      "requiredPorts": [
        "evaluation"
      ],
      "authoringStrategy": "server_activity"
    }
  },
  {
    "componentId": "didact.timeline-steps",
    "manifestId": "didact.timeline",
    "exportName": "Timeline",
    "registryItem": "timeline",
    "maturity": "stable",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "Timeline",
      "registryItem": "timeline",
      "sourceModule": "timeline"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "Timeline"
    },
    "operations": {
      "rendererMode": "direct",
      "rendererSymbol": "DidactTimeline",
      "emission": "enabled",
      "requiredPorts": [],
      "authoringStrategy": "inline"
    }
  },
  {
    "componentId": "didact.practice-set",
    "manifestId": "didact.practice-set",
    "exportName": "PracticeSet",
    "registryItem": "practice-set",
    "maturity": "stable",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "PracticeSet",
      "registryItem": "practice-set",
      "sourceModule": "practice-set"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "PracticeSet"
    },
    "operations": {
      "rendererMode": "blocked",
      "rendererSymbol": null,
      "emission": "disabled",
      "requiredPorts": [
        "evaluation"
      ],
      "authoringStrategy": "unsupported"
    }
  },
  {
    "componentId": "didact.retrieval-practice-session",
    "manifestId": "didact.retrieval-practice-session",
    "exportName": "RetrievalPracticeSession",
    "registryItem": "retrieval-practice-session",
    "maturity": "stable",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "RetrievalPracticeSession",
      "registryItem": "retrieval-practice-session",
      "sourceModule": "retrieval-practice-session"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "RetrievalPracticeSession"
    },
    "operations": {
      "rendererMode": "blocked",
      "rendererSymbol": null,
      "emission": "disabled",
      "requiredPorts": [
        "persistence",
        "scheduler"
      ],
      "authoringStrategy": "unsupported"
    }
  },
  {
    "componentId": "didact.self-explanation-prompt",
    "manifestId": "didact.self-explanation-prompt",
    "exportName": "SelfExplanationPrompt",
    "registryItem": "generative-learning",
    "maturity": "stable",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "SelfExplanationPrompt",
      "registryItem": "generative-learning",
      "sourceModule": "generative-learning"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "SelfExplanationPrompt"
    },
    "operations": {
      "rendererMode": "activity_definition",
      "rendererSymbol": "DidactActivity",
      "emission": "enabled",
      "requiredPorts": [
        "persistence"
      ],
      "authoringStrategy": "server_activity"
    }
  },
  {
    "componentId": "didact.worked-example",
    "manifestId": "didact.worked-example",
    "exportName": "WorkedExample",
    "registryItem": "generative-learning",
    "maturity": "stable",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "WorkedExample",
      "registryItem": "generative-learning",
      "sourceModule": "generative-learning"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "WorkedExample"
    },
    "operations": {
      "rendererMode": "direct",
      "rendererSymbol": "DidactWorkedExample",
      "emission": "enabled",
      "requiredPorts": [],
      "authoringStrategy": "inline"
    }
  },
  {
    "componentId": "didact.completion-problem",
    "manifestId": "didact.completion-problem",
    "exportName": "CompletionProblem",
    "registryItem": "generative-learning",
    "maturity": "stable",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "CompletionProblem",
      "registryItem": "generative-learning",
      "sourceModule": "generative-learning"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "CompletionProblem"
    },
    "operations": {
      "rendererMode": "activity_definition",
      "rendererSymbol": "DidactActivity",
      "emission": "enabled",
      "requiredPorts": [
        "evaluation"
      ],
      "authoringStrategy": "server_activity"
    }
  },
  {
    "componentId": "didact.numeric-question",
    "manifestId": "didact.numeric-question",
    "exportName": "NumericQuestion",
    "registryItem": "numeric-question",
    "maturity": "stable",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "NumericQuestion",
      "registryItem": "numeric-question",
      "sourceModule": "numeric-question"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "NumericQuestion"
    },
    "operations": {
      "rendererMode": "activity_definition",
      "rendererSymbol": "DidactActivity",
      "emission": "enabled",
      "requiredPorts": [
        "evaluation"
      ],
      "authoringStrategy": "server_activity"
    }
  },
  {
    "componentId": "didact.word-bank",
    "manifestId": "didact.word-bank",
    "exportName": "WordBank",
    "registryItem": "word-bank",
    "maturity": "stable",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "WordBank",
      "registryItem": "word-bank",
      "sourceModule": "word-bank"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "WordBank"
    },
    "operations": {
      "rendererMode": "activity_definition",
      "rendererSymbol": "DidactActivity",
      "emission": "enabled",
      "requiredPorts": [
        "evaluation"
      ],
      "authoringStrategy": "server_activity"
    }
  },
  {
    "componentId": "didact.hotspot",
    "manifestId": "didact.hotspot",
    "exportName": "Hotspot",
    "registryItem": "hotspot",
    "maturity": "stable",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "Hotspot",
      "registryItem": "hotspot",
      "sourceModule": "hotspot"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "Hotspot"
    },
    "operations": {
      "rendererMode": "activity_definition",
      "rendererSymbol": "DidactActivity",
      "emission": "enabled",
      "requiredPorts": [
        "assets",
        "evaluation"
      ],
      "authoringStrategy": "server_activity"
    }
  },
  {
    "componentId": "didact.interactive-media",
    "manifestId": "didact.interactive-media",
    "exportName": "InteractiveMedia",
    "registryItem": "interactive-media",
    "maturity": "experimental",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "InteractiveMedia",
      "registryItem": "interactive-media",
      "sourceModule": "interactive-media"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "InteractiveMedia"
    },
    "operations": {
      "rendererMode": "activity_definition",
      "rendererSymbol": "DidactActivity",
      "emission": "enabled",
      "requiredPorts": [
        "assets",
        "persistence"
      ],
      "authoringStrategy": "server_activity"
    }
  },
  {
    "componentId": "didact.data-explorer",
    "manifestId": "didact.data-explorer",
    "exportName": "DataExplorer",
    "registryItem": "data-explorer",
    "maturity": "experimental",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "DataExplorer",
      "registryItem": "data-explorer",
      "sourceModule": "data-explorer"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "DataExplorer"
    },
    "operations": {
      "rendererMode": "activity_definition",
      "rendererSymbol": "DidactActivity",
      "emission": "enabled",
      "requiredPorts": [],
      "authoringStrategy": "server_activity"
    }
  },
  {
    "componentId": "didact.branching-scenario",
    "manifestId": "didact.branching-scenario",
    "exportName": "BranchingScenario",
    "registryItem": "branching-scenario",
    "maturity": "experimental",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "BranchingScenario",
      "registryItem": "branching-scenario",
      "sourceModule": "branching-scenario"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "BranchingScenario"
    },
    "operations": {
      "rendererMode": "blocked",
      "rendererSymbol": null,
      "emission": "disabled",
      "requiredPorts": [],
      "authoringStrategy": "unsupported"
    }
  },
  {
    "componentId": "didact.simulation-lab",
    "manifestId": "didact.simulation-lab",
    "exportName": "SimulationLab",
    "registryItem": "simulation-lab",
    "maturity": "experimental",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "SimulationLab",
      "registryItem": "simulation-lab",
      "sourceModule": "simulation-lab"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "SimulationLab"
    },
    "operations": {
      "rendererMode": "blocked",
      "rendererSymbol": null,
      "emission": "disabled",
      "requiredPorts": [
        "simulation"
      ],
      "authoringStrategy": "unsupported"
    }
  },
  {
    "componentId": "didact.code-exercise",
    "manifestId": "didact.code-exercise",
    "exportName": "CodeExercise",
    "registryItem": "code-exercise",
    "maturity": "experimental",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "CodeExercise",
      "registryItem": "code-exercise",
      "sourceModule": "code-exercise"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "CodeExercise"
    },
    "operations": {
      "rendererMode": "blocked",
      "rendererSymbol": null,
      "emission": "disabled",
      "requiredPorts": [
        "evaluation",
        "execution"
      ],
      "authoringStrategy": "unsupported"
    }
  },
  {
    "componentId": "didact.label-diagram",
    "manifestId": "didact.label-diagram",
    "exportName": "LabelDiagram",
    "registryItem": "label-diagram",
    "maturity": "stable",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "LabelDiagram",
      "registryItem": "label-diagram",
      "sourceModule": "label-diagram"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "LabelDiagram"
    },
    "operations": {
      "rendererMode": "activity_definition",
      "rendererSymbol": "DidactActivity",
      "emission": "enabled",
      "requiredPorts": [
        "assets",
        "evaluation"
      ],
      "authoringStrategy": "server_activity"
    }
  },
  {
    "componentId": "didact.concept-map",
    "manifestId": "didact.concept-map",
    "exportName": "ConceptMap",
    "registryItem": "concept-map",
    "maturity": "stable",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "ConceptMap",
      "registryItem": "concept-map",
      "sourceModule": "concept-map"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "ConceptMap"
    },
    "operations": {
      "rendererMode": "activity_definition",
      "rendererSymbol": "DidactActivity",
      "emission": "enabled",
      "requiredPorts": [
        "evaluation",
        "persistence"
      ],
      "authoringStrategy": "server_activity"
    }
  },
  {
    "componentId": "didact.drawing-response",
    "manifestId": "didact.drawing-response",
    "exportName": "DrawingResponse",
    "registryItem": "drawing-response",
    "maturity": "stable",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "DrawingResponse",
      "registryItem": "drawing-response",
      "sourceModule": "drawing-response"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "DrawingResponse"
    },
    "operations": {
      "rendererMode": "activity_definition",
      "rendererSymbol": "DidactActivity",
      "emission": "enabled",
      "requiredPorts": [
        "evaluation",
        "persistence"
      ],
      "authoringStrategy": "server_activity"
    }
  },
  {
    "componentId": "didact.equation-workbench",
    "manifestId": "didact.equation-workbench",
    "exportName": "EquationWorkbench",
    "registryItem": "equation-workbench",
    "maturity": "stable",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "EquationWorkbench",
      "registryItem": "equation-workbench",
      "sourceModule": "equation-workbench"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "EquationWorkbench"
    },
    "operations": {
      "rendererMode": "activity_definition",
      "rendererSymbol": "DidactActivity",
      "emission": "enabled",
      "requiredPorts": [
        "evaluation"
      ],
      "authoringStrategy": "server_activity"
    }
  },
  {
    "componentId": "didact.evidence-annotation",
    "manifestId": "didact.evidence-annotation",
    "exportName": "EvidenceAnnotation",
    "registryItem": "evidence-annotation",
    "maturity": "stable",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "EvidenceAnnotation",
      "registryItem": "evidence-annotation",
      "sourceModule": "evidence-annotation"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "EvidenceAnnotation"
    },
    "operations": {
      "rendererMode": "activity_definition",
      "rendererSymbol": "DidactActivity",
      "emission": "enabled",
      "requiredPorts": [
        "evaluation",
        "persistence"
      ],
      "authoringStrategy": "server_activity"
    }
  },
  {
    "componentId": "didact.measurement-lab",
    "manifestId": "didact.measurement-lab",
    "exportName": "MeasurementLab",
    "registryItem": "measurement-lab",
    "maturity": "stable",
    "didactVersion": "1.0.0",
    "lazyModule": {
      "strategy": "vendor-export",
      "exportName": "MeasurementLab",
      "registryItem": "measurement-lab",
      "sourceModule": "measurement-lab"
    },
    "adapter": {
      "rendererAvailable": true,
      "rendererSymbol": "MeasurementLab"
    },
    "operations": {
      "rendererMode": "activity_definition",
      "rendererSymbol": "DidactActivity",
      "emission": "enabled",
      "requiredPorts": [
        "evaluation"
      ],
      "authoringStrategy": "server_activity"
    }
  }
] as const satisfies readonly DidactRegistryEntry[]

export const DIDACT_COMPONENT_BY_ID: ReadonlyMap<string, DidactRegistryEntry> = new Map(
  DIDACT_COMPONENT_REGISTRY.map((entry) => [entry.componentId, entry]),
)
