/* eslint-disable */
// Generated by scripts/generate-didact-registry.mjs. Dynamic imports exist only for
// host-ready adapters; unavailable entries fail explicitly without importing raw vendor code.
import {
  type DidactComponentLoaderEntry,
  type DidactModuleLoader,
} from './loader-types'

const moduleLoaders: Readonly<Record<string, DidactModuleLoader>> = {
  "flashcard": () => import("../../../vendor/didact/source/packages/core/src/components/flashcard"),
  "matching-exercises": () => import("../../../vendor/didact/source/packages/core/src/components/matching-exercises"),
  "quiz-item": () => import("../../../vendor/didact/source/packages/core/src/components/quiz-item"),
  "glossary": () => import("../../../vendor/didact/source/packages/core/src/components/glossary"),
  "hint-reveal": () => import("../../../vendor/didact/source/packages/core/src/components/hint-reveal"),
  "progress-indicators": () => import("../../../vendor/didact/source/packages/core/src/components/progress-indicator"),
  "mastery-badge": () => import("../../../vendor/didact/source/packages/core/src/components/mastery-badge"),
  "rubric": () => import("../../../vendor/didact/source/packages/core/src/components/rubric"),
  "timeline": () => import("../../../vendor/didact/source/packages/core/src/components/timeline"),
  "practice-set": () => import("../../../vendor/didact/source/packages/core/src/components/practice-set"),
  "retrieval-practice-session": () => import("../../../vendor/didact/source/packages/core/src/components/retrieval-practice-session"),
  "generative-learning": () => import("../../../vendor/didact/source/packages/core/src/components/generative-learning"),
  "numeric-question": () => import("../../../vendor/didact/source/packages/core/src/components/numeric-question"),
  "word-bank": () => import("../../../vendor/didact/source/packages/core/src/components/word-bank"),
  "hotspot": () => import("../../../vendor/didact/source/packages/core/src/components/hotspot"),
  "interactive-media": () => import("../../../vendor/didact/source/packages/core/src/components/interactive-media"),
  "data-explorer": () => import("../../../vendor/didact/source/packages/core/src/components/data-explorer"),
  "branching-scenario": () => import("../../../vendor/didact/source/packages/core/src/components/branching-scenario"),
  "simulation-lab": () => import("../../../vendor/didact/source/packages/core/src/components/simulation-lab"),
  "code-exercise": () => import("../../../vendor/didact/source/packages/core/src/components/code-exercise"),
  "label-diagram": () => import("../../../vendor/didact/source/packages/core/src/components/label-diagram"),
  "concept-map": () => import("../../../vendor/didact/source/packages/core/src/components/concept-map"),
  "drawing-response": () => import("../../../vendor/didact/source/packages/core/src/components/drawing-response"),
  "equation-workbench": () => import("../../../vendor/didact/source/packages/core/src/components/equation-workbench"),
  "evidence-annotation": () => import("../../../vendor/didact/source/packages/core/src/components/evidence-annotation"),
  "measurement-lab": () => import("../../../vendor/didact/source/packages/core/src/components/measurement-lab"),
}

export const DIDACT_COMPONENT_LOADERS = {
  "didact.flashcard": {
    componentId: "didact.flashcard",
    exportName: "Flashcard",
    registryItem: "flashcard",
    loadModule: moduleLoaders["flashcard"],
  },
  "didact.matching": {
    componentId: "didact.matching",
    exportName: "MatchingExercise",
    registryItem: "matching-exercises",
    loadModule: moduleLoaders["matching-exercises"],
  },
  "didact.sort": {
    componentId: "didact.sort",
    exportName: "SortExercise",
    registryItem: "matching-exercises",
    loadModule: moduleLoaders["matching-exercises"],
  },
  "didact.categorize": {
    componentId: "didact.categorize",
    exportName: "CategorizeExercise",
    registryItem: "matching-exercises",
    loadModule: moduleLoaders["matching-exercises"],
  },
  "didact.quiz.single-choice": {
    componentId: "didact.quiz.single-choice",
    exportName: "SingleChoiceQuiz",
    registryItem: "quiz-item",
    loadModule: moduleLoaders["quiz-item"],
  },
  "didact.quiz.multi-select": {
    componentId: "didact.quiz.multi-select",
    exportName: "MultiSelectQuiz",
    registryItem: "quiz-item",
    loadModule: moduleLoaders["quiz-item"],
  },
  "didact.quiz.true-false": {
    componentId: "didact.quiz.true-false",
    exportName: "TrueFalseQuiz",
    registryItem: "quiz-item",
    loadModule: moduleLoaders["quiz-item"],
  },
  "didact.quiz.fill-in-the-blank": {
    componentId: "didact.quiz.fill-in-the-blank",
    exportName: "FillInTheBlankQuiz",
    registryItem: "quiz-item",
    loadModule: moduleLoaders["quiz-item"],
  },
  "didact.quiz.short-answer": {
    componentId: "didact.quiz.short-answer",
    exportName: "ShortAnswerQuiz",
    registryItem: "quiz-item",
    loadModule: moduleLoaders["quiz-item"],
  },
  "didact.glossary-term": {
    componentId: "didact.glossary-term",
    exportName: "Glossary",
    registryItem: "glossary",
    loadModule: moduleLoaders["glossary"],
  },
  "didact.hint-reveal": {
    componentId: "didact.hint-reveal",
    exportName: "HintReveal",
    registryItem: "hint-reveal",
    loadModule: moduleLoaders["hint-reveal"],
  },
  "didact.progress": {
    componentId: "didact.progress",
    exportName: "ProgressIndicator",
    registryItem: "progress-indicators",
    loadModule: moduleLoaders["progress-indicators"],
  },
  "didact.mastery-badge": {
    componentId: "didact.mastery-badge",
    exportName: "MasteryBadge",
    registryItem: "mastery-badge",
    loadModule: moduleLoaders["mastery-badge"],
  },
  "didact.rubric": {
    componentId: "didact.rubric",
    exportName: "Rubric",
    registryItem: "rubric",
    loadModule: moduleLoaders["rubric"],
  },
  "didact.timeline-steps": {
    componentId: "didact.timeline-steps",
    exportName: "Timeline",
    registryItem: "timeline",
    loadModule: moduleLoaders["timeline"],
  },
  "didact.practice-set": {
    componentId: "didact.practice-set",
    exportName: "PracticeSet",
    registryItem: "practice-set",
    loadModule: moduleLoaders["practice-set"],
  },
  "didact.retrieval-practice-session": {
    componentId: "didact.retrieval-practice-session",
    exportName: "RetrievalPracticeSession",
    registryItem: "retrieval-practice-session",
    loadModule: moduleLoaders["retrieval-practice-session"],
  },
  "didact.self-explanation-prompt": {
    componentId: "didact.self-explanation-prompt",
    exportName: "SelfExplanationPrompt",
    registryItem: "generative-learning",
    loadModule: moduleLoaders["generative-learning"],
  },
  "didact.worked-example": {
    componentId: "didact.worked-example",
    exportName: "WorkedExample",
    registryItem: "generative-learning",
    loadModule: moduleLoaders["generative-learning"],
  },
  "didact.completion-problem": {
    componentId: "didact.completion-problem",
    exportName: "CompletionProblem",
    registryItem: "generative-learning",
    loadModule: moduleLoaders["generative-learning"],
  },
  "didact.numeric-question": {
    componentId: "didact.numeric-question",
    exportName: "NumericQuestion",
    registryItem: "numeric-question",
    loadModule: moduleLoaders["numeric-question"],
  },
  "didact.word-bank": {
    componentId: "didact.word-bank",
    exportName: "WordBank",
    registryItem: "word-bank",
    loadModule: moduleLoaders["word-bank"],
  },
  "didact.hotspot": {
    componentId: "didact.hotspot",
    exportName: "Hotspot",
    registryItem: "hotspot",
    loadModule: moduleLoaders["hotspot"],
  },
  "didact.interactive-media": {
    componentId: "didact.interactive-media",
    exportName: "InteractiveMedia",
    registryItem: "interactive-media",
    loadModule: moduleLoaders["interactive-media"],
  },
  "didact.data-explorer": {
    componentId: "didact.data-explorer",
    exportName: "DataExplorer",
    registryItem: "data-explorer",
    loadModule: moduleLoaders["data-explorer"],
  },
  "didact.branching-scenario": {
    componentId: "didact.branching-scenario",
    exportName: "BranchingScenario",
    registryItem: "branching-scenario",
    loadModule: moduleLoaders["branching-scenario"],
  },
  "didact.simulation-lab": {
    componentId: "didact.simulation-lab",
    exportName: "SimulationLab",
    registryItem: "simulation-lab",
    loadModule: moduleLoaders["simulation-lab"],
  },
  "didact.code-exercise": {
    componentId: "didact.code-exercise",
    exportName: "CodeExercise",
    registryItem: "code-exercise",
    loadModule: moduleLoaders["code-exercise"],
  },
  "didact.label-diagram": {
    componentId: "didact.label-diagram",
    exportName: "LabelDiagram",
    registryItem: "label-diagram",
    loadModule: moduleLoaders["label-diagram"],
  },
  "didact.concept-map": {
    componentId: "didact.concept-map",
    exportName: "ConceptMap",
    registryItem: "concept-map",
    loadModule: moduleLoaders["concept-map"],
  },
  "didact.drawing-response": {
    componentId: "didact.drawing-response",
    exportName: "DrawingResponse",
    registryItem: "drawing-response",
    loadModule: moduleLoaders["drawing-response"],
  },
  "didact.equation-workbench": {
    componentId: "didact.equation-workbench",
    exportName: "EquationWorkbench",
    registryItem: "equation-workbench",
    loadModule: moduleLoaders["equation-workbench"],
  },
  "didact.evidence-annotation": {
    componentId: "didact.evidence-annotation",
    exportName: "EvidenceAnnotation",
    registryItem: "evidence-annotation",
    loadModule: moduleLoaders["evidence-annotation"],
  },
  "didact.measurement-lab": {
    componentId: "didact.measurement-lab",
    exportName: "MeasurementLab",
    registryItem: "measurement-lab",
    loadModule: moduleLoaders["measurement-lab"],
  },
} as const satisfies Readonly<Record<string, DidactComponentLoaderEntry>>

export async function loadDidactExport(componentId: string): Promise<unknown> {
  if (!(componentId in DIDACT_COMPONENT_LOADERS)) {
    throw new Error(`Unknown Didact component ${componentId}`)
  }
  const knownId = componentId as keyof typeof DIDACT_COMPONENT_LOADERS
  const entry = DIDACT_COMPONENT_LOADERS[knownId]
  const module = await entry.loadModule()
  const component = module[entry.exportName]
  if (component === undefined) {
    throw new Error(`Didact module ${entry.registryItem} does not export ${entry.exportName}`)
  }
  return component
}
