"""Pure planning primitives for personalization experiments."""

from src.personalization.didact_catalog import (
    AvailabilityStatus,
    DidactCatalog,
    DidactCatalogError,
    DidactComponentAvailability,
    EmissionStatus,
    HostPort,
    load_didact_catalog,
)
from src.personalization.didact_descriptors import (
    DidactExposureError,
    export_didact_descriptors,
    openui_names_for_shortlist,
)
from src.personalization.plan import (
    AccessibilityCapability,
    CognitiveMission,
    ComponentCandidate,
    ComponentDescriptor,
    Decline,
    DeclineReason,
    Declined,
    ErrorSignal,
    InferredPresentationBucket,
    LearningExperiencePlan,
    LearningObjective,
    PersonalizationProjection,
    Presentation,
    ProducerKind,
    SourceFunction,
    SupportBand,
    SupportPolicy,
    plan_experience,
)
from src.personalization.projection import project_runtime_signals

__all__ = [
    "AccessibilityCapability",
    "AvailabilityStatus",
    "CognitiveMission",
    "ComponentCandidate",
    "ComponentDescriptor",
    "Decline",
    "DeclineReason",
    "Declined",
    "DidactCatalog",
    "DidactCatalogError",
    "DidactComponentAvailability",
    "DidactExposureError",
    "EmissionStatus",
    "ErrorSignal",
    "HostPort",
    "InferredPresentationBucket",
    "LearningExperiencePlan",
    "LearningObjective",
    "PersonalizationProjection",
    "Presentation",
    "ProducerKind",
    "SourceFunction",
    "SupportBand",
    "SupportPolicy",
    "plan_experience",
    "export_didact_descriptors",
    "load_didact_catalog",
    "openui_names_for_shortlist",
    "project_runtime_signals",
]
