"""The render backend seam of §5.4.

Only one dialect ships in this PR (``openui``). The ``Protocol`` and the registry
exist so a second one is a new file plus one registry entry, and so nothing outside
``src/render/backends/`` ever touches dialect text.

``prompt_fragment`` used to be part of this contract and no longer is: the prompt is
generated by OpenUI's own ``library.prompt()`` at build time and read from
``src/render/prompt.py``. A backend now *validates* a dialect and *writes* it back; it
does not teach it.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from src.render.spec import UISpec


@runtime_checkable
class RenderBackend(Protocol):
    """A dialect the LLM can emit and this process can parse."""

    name: str

    def parse(self, raw: str, *, ui_format: str | None = None) -> UISpec:
        """Parse a complete program. Raises ``RenderParseError``."""
        ...

    def parse_partial(self, raw: str, *, ui_format: str | None = None) -> UISpec:
        """Tolerant parse of incomplete output (streaming).

        Drops the last line when it is half-written. Never raises. Still needed on the
        server even though the browser parses too: what streams to the browser is the
        canonical re-serialization of the prefix, never the model's own bytes.
        """
        ...

    def serialize(self, spec: UISpec) -> str:
        """Spec -> canonical program text. The only text the client may receive."""
        ...


__all__ = ["RenderBackend"]
