"""The ``openui`` dialect — the server-side gate on generated programs (§5.4).

A **subset** of OpenUI Lang, parsed in Python. Line-oriented, one declaration per
*logical* line, **positional** arguments in the order of the kit table, children as
arrays:

    root = Stack([intro, steps, quiz], "md")
    intro = TextContent("Las devoluciones se aceptan durante 30 dias.", "lead")

A child may be written as a reference (above) or **inline** (below); both are the same
program once parsed, and :func:`_expand` flattens the inline form into the flat
``UISpec`` list with a synthetic id::

    root = Stack([TextContent("Las devoluciones se aceptan durante 30 dias.", "lead")], "md")
    # parses to the two components above, the inline one named `root_1`

Inline nesting was rejected until 2026-07-27 and that was **our** bug, not the model's:
the prompt this repository serves is generated by ``library.prompt()`` and says, in the
signature block, *"Sub-components can be inline or referenced; prefer references for
better streaming"*. Measured against ``qwen2.5:7b-instruct``, teaching a construction and
then refusing it cost a whole repair loop, because the parse error also misdiagnosed the
cause (see :meth:`_Scanner.missing_separator` and the note on error messages). ``serialize``
still writes the **referenced** form only — that is the canonical text, it is what their
prompt recommends for streaming, and it is what gives every block a real statement id in
the browser (an inline node parses with ``statementId: null`` there, which
``node_render_views`` cannot key on).

Since the adoption of the real dependency (2026-07-26, ``docs/design/openui-adoption.md``)
this module has **one** job and no longer has two:

* It **no longer teaches the dialect.** ``library.prompt()`` does, from the frontend kit,
  through the build-step artefacts that ``src/render/prompt.py`` reads. There is exactly
  one place where the catalogue is declared, and it is not here.
* It **still validates**, and it is the last gate before anything is persisted or served.
  The frozen grammar below has no production for ``$state``, ``{objects}``, ``@builtins``,
  ternaries, arithmetic, ``Query()`` or ``Mutation()``, so reactivity is *inexpressible*
  rather than blacklisted — which is why this parser was kept when the browser got its
  own. Their parser accepts a stray ``Mutation("delete_all_users", {...})`` with
  ``meta.errors == []``; this one cannot represent it. ``src/render/gate.py`` is the cheap
  door in front, ``serialize`` produces the canonical text the browser is allowed to see.

The standard is still wider than this subset: it accepts literal newlines inside strings,
booleans, ``null``, objects, arithmetic, ``//`` comments and markdown fences. It does
**not** require one declaration per physical line, and neither does this parser any more:
``src/render/lines.py`` joins the physical lines of a declaration the way
``lang-core``'s own statement splitter does (a newline inside an open bracket is not a
separator), and that module carries the measurement that forced the change. What is still
ours and not the standard's is the narrower half of escape rule 3: **a text value closes
its quote on the line that opened it**, which is what keeps ``parse_partial`` cheap.

Every error message this file raises is part of the contract with the LLM, not prose for
a human: the repair loop feeds them back verbatim (``build_repair_prompt``), so a message
that **guesses** the cause makes the model fix code that was never broken and the loop
stops converging. The rule here is therefore: name only what was actually observed, and
say what to write instead.

The frozen grammar, which this file *is* the implementation of. It used to be exported as
``GRAMMAR`` because it was pasted into the prompt; the prompt now comes from
``library.prompt()``, so it lives here as the specification of the gate and nothing reads
it as data::

    program    = { line } ;
    line       = ident "=" call line_break ;
    ident      = letter { letter | "0".."9" | "_" } ;   (* folded to ASCII, see below *)
    call       = comp_name "(" [ arg { "," arg } ] ")" ;
    comp_name  = "Stack" | "TextContent" | "Card" | "Callout" | "StepSequence"
               | "Table" | "CodeBlock" | "Chart" | "QuizItem" ;
    arg        = string | number | array | ident | call ;
    array      = "[" [ arg { "," arg } ] "]" ;
    string     = '"' { char | escape } '"' ;
    escape     = "\\" ( '"' | "\\" | "n" ) ;
    char       = <cualquier caracter excepto '"', '\\' y newline> ;
    number     = [ "-" ] digit { digit } [ "." digit { digit } ] ;

``line_break`` is a newline at bracket depth zero, not any newline: see
``src/render/lines.py``.

``letter`` is any Unicode letter, and the id is then **folded to ASCII** by
:func:`fold_identifier`, so ``conclusión`` is accepted and becomes ``conclusion``. This
is the one place where this parser is deliberately *wider* than ``lang-core``, and the
reason is that ``lang-core`` is narrower than it looks: its tokenizer takes identifiers
from ``[A-Za-z_][A-Za-z0-9_]*`` only, and the character it cannot classify it **silently
skips** (``dist/index.mjs``, the trailing ``i++`` of ``tokenize``). ``conclusión`` in the
browser is therefore not an error, it is two identifiers and a dropped statement — the
worst possible outcome for a validator whose job is to decide what may be served. So the
id cannot travel as written; but it also does not have to be refused, because it is
unambiguous. Folding it and serializing the folded form gives the browser the pure-ASCII
text its tokenizer needs, deterministically, and costs nothing: block ids are statement
keys and are never shown to the learner.

Measured, this was the single most expensive defect in the corpus: ``groq/llama-3.1-8b-instant``
failed ``atencion-reclamaciones`` **3 passes out of 3** on ``conclusión``
(``bench_out/failures/quality-20260727-030727``), both attempts each time, because the
product is Spanish and a Spanish-speaking model names its variables in Spanish. Note that
this is *not* the 79ede73 case — our grammar was not a strict subset here, both were ASCII
— which is why the fix is a normalisation and not a widening.

Two constraints the EBNF cannot state:

* A ``call`` as an ``arg`` is only meaningful where the kit declares a ``ref[]`` prop
  (``Stack.children``, ``Card.children``). Anywhere else it is a typed error, named as
  such rather than reported as a stray parenthesis.
* Nesting is capped at :data:`MAX_NESTING_DEPTH` levels per line, so a recursive or
  pathological program cannot pick the CPython recursion limit as its denial of service.

Two things the dialect does **not** carry, and how they are recovered:

* ``root`` — the id no other component lists among its children. Ties fall back to a
  component literally named ``root``, then to the first line.
* ``format`` — inferred from the component mix by :func:`infer_format`, unless the
  caller passes ``ui_format=`` (which is what the runtime does, since
  ``decide_formato`` already decided it). The inference and ``serialize`` agree, so
  ``parse(serialize(spec)) == spec`` holds without a header line, which the frozen
  grammar has no room for.
"""

from __future__ import annotations

import re
import unicodedata
from typing import Any, NamedTuple, NoReturn

from pydantic import ValidationError as PydanticValidationError

from src.render.errors import RenderError, RenderParseError
from src.render.kit import (
    LLM_COMPONENT_NAMES,
    UI_KIT,
    ComponentSpec,
    PropKind,
    PropSpec,
)
from src.render.lines import LogicalLine, logical_lines
from src.render.spec import (
    UI_SPEC_VERSION,
    Component,
    UISpec,
    flatten_validation_error,
    parse_spec,
)

#: An identifier as *written*: any Unicode letter or ``_`` to start, then letters,
#: digits, ``_`` and combining marks. ``[^\W\d]`` is 'a word character
#: that is not a digit'; the explicit \u0300-\u036f range picks up the
#: *decomposed* form of an accent, which ``\w`` does not match (a combining mark
#: is not alphanumeric). Every id that comes out of here goes through
#: :func:`fold_identifier` before it is used, so nothing downstream -- the ``UISpec``,
#: ``serialize``, the browser -- ever sees a non-ASCII id.
_IDENT_PATTERN = r"[^\W\d][\w\u0300-\u036f]*"
_IDENT_RE = re.compile(_IDENT_PATTERN, re.UNICODE)
_LINE_RE = re.compile(
    rf"^[ \t]*({_IDENT_PATTERN})[ \t]*=[ \t]*", re.UNICODE
)
_NUMBER_RE = re.compile(r"-?[0-9]+(?:\.[0-9]+)?")

#: What a folded identifier is allowed to be. Same production ``src/render/spec.py``
#: enforces on ``Component.id``, and the same one ``lang-core``'s tokenizer implements.
_ASCII_IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

#: Content-bearing components. Used only by :func:`infer_format`.
_CONTENT_TYPES = frozenset(UI_KIT.names) - {"Stack", "Card", "QuizItem"}

#: How many nested ``(`` / ``[`` one line may open. Rule 4 caps a spec at 12 components
#: and the gate caps a line at 4 kB, neither of which bounds *depth*: without this cap a
#: single hostile line could pick the CPython recursion limit as its denial of service,
#: and the failure would be a ``RecursionError`` (a 500) instead of a repairable message.
#: Sixteen is far past anything a lesson needs — the deepest valid fixture opens three.
MAX_NESTING_DEPTH = 16

#: Separator that joins a synthetic id to its owner. ``root_1``, ``root_2``, ``root_1_1``.
_SYNTHETIC_SEP = "_"


#: The alphabet :func:`fold_identifier` keeps. Spelled out rather than derived from a
#: regex so the fold cannot quietly widen when the regex is edited.
_ASCII_ID_CHARS = frozenset(
    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_"
)


def fold_identifier(name: str) -> str:
    """``conclusión`` -> ``conclusion``. ``""`` when nothing usable survives.

    NFKD splits an accented letter into its base plus a combining mark; dropping the
    marks and everything else outside ``[A-Za-z0-9_]`` leaves the ASCII the browser's
    tokenizer can actually carry. Pure ASCII in, the same string out — this is a no-op on
    every id the corpus has ever produced except the accented ones, which is what makes
    it safe to run on all of them.

    Deterministic by construction (no dict order, no locale, no case folding), because
    the folded id is what the ``cache_key``, the round trip and ``node_render_views`` all
    compare across runs.
    """
    decomposed = unicodedata.normalize("NFKD", name)
    folded = "".join(
        char for char in decomposed if char in _ASCII_ID_CHARS
    )
    return folded if _ASCII_IDENT_RE.match(folded) else ""


class _Ref(NamedTuple):
    """An ``ident`` argument: a reference to another component."""

    name: str


class _Call(NamedTuple):
    """An inline component call used as an argument: ``Stack([TextContent(...)], "md")``.

    Never reaches a ``Component``: :func:`_expand` turns every one of these into its own
    statement with a synthetic id before anything is validated.
    """

    name: str
    args: list[Any]


class _Statement(NamedTuple):
    """One ``ident = Componente(args)`` declaration, before it becomes a ``Component``."""

    ident: str
    comp_name: str
    args: list[Any]
    line_no: int
    line: str


class _Scanner:
    """Single-line recursive-descent scanner over the ``call`` production."""

    def __init__(self, text: str, line_no: int, pos: int = 0) -> None:
        self.text = text
        self.line_no = line_no
        self.pos = pos
        self.depth = 0
        #: What :meth:`value` produced last. Read only to diagnose a missing separator
        #: with evidence instead of with a guess.
        self.last_value = ""

    # -- primitives ----------------------------------------------------------------

    def fail(self, message: str) -> NoReturn:
        raise RenderParseError(
            f"{message} (col {self.pos + 1})", line_no=self.line_no, line=self.text
        )

    @property
    def eof(self) -> bool:
        return self.pos >= len(self.text)

    def peek(self) -> str:
        return "" if self.eof else self.text[self.pos]

    def skip_ws(self) -> None:
        while not self.eof and self.text[self.pos] in " \t":
            self.pos += 1

    def expect_open(self) -> None:
        """The ``(`` of a call. Its absence has exactly one cause worth naming."""
        self.skip_ws()
        if self.peek() != "(":
            found = self.peek() or "the end of the line"
            self.fail(
                f"expected '(' after the component name, found {found!r}: every "
                "declaration is a call, 'id = Componente(argumentos)'"
            )
        self.pos += 1

    def enter(self) -> None:
        self.depth += 1
        if self.depth > MAX_NESTING_DEPTH:
            self.fail(
                f"nesting goes deeper than {MAX_NESTING_DEPTH} levels: write the inner "
                "blocks as their own 'id = Componente(...)' lines and put their ids here"
            )

    def leave(self) -> None:
        self.depth -= 1

    def missing_separator(self, expected: str, closing: str) -> NoReturn:
        """Fail on a value that is not followed by ``,`` or its closing bracket.

        Every branch below names a cause it has **checked**. The message this replaced
        blamed an unescaped double quote unconditionally; measured against a real 7B, an
        inline component call got that message, the repair loop re-injected it, and the
        model spent three attempts moving quotes that were already correct.
        """
        char = self.peek()
        if char == "=":
            self.fail(
                f"expected {expected}, found '=': this dialect has no named arguments. "
                'Pass the values in order and without their name — Stack([intro], "md"), '
                'never Stack(children = [intro], gap = "md")'
            )
        if self.last_value == "string":
            # Two causes fit this evidence and neither can be ruled out from here, so
            # both are stated. Naming only one of them is what broke the repair loop.
            self.fail(
                f"expected {expected} after the text value, found {char!r}: the text "
                "ended at the double quote before it. Either the separator is missing, "
                'or the text itself holds a double quote, which is written \\"'
            )
        self.fail(
            f"expected {expected}, found {char!r}: separate the values with ',' and "
            f"close with {closing!r}"
        )

    # -- productions ---------------------------------------------------------------

    def comp_name(self) -> str:
        self.skip_ws()
        match = _IDENT_RE.match(self.text, self.pos)
        if match is None:
            found = self.peek() or "the end of the line"
            self.fail(
                f"expected a component name after '=', found {found!r}: a line is "
                "'id = Componente(argumentos)'"
            )
        self.pos = match.end()
        return match.group()

    def string(self) -> str:
        self.pos += 1  # the opening quote
        out: list[str] = []
        while True:
            if self.eof:
                self.fail(
                    "unterminated text value: a string must close its quote on the "
                    'same line (write \\n for a line break, \\" for a quote)'
                )
            char = self.text[self.pos]
            if char == '"':
                self.pos += 1
                return "".join(out)
            if char == "\\":
                self.pos += 1
                if self.eof:
                    self.fail("unterminated escape at end of line")
                escaped = self.text[self.pos]
                if escaped == "n":
                    out.append("\n")
                elif escaped in ('"', "\\"):
                    out.append(escaped)
                else:
                    self.fail(
                        f"invalid escape '\\{escaped}': only \\\", \\\\ and \\n exist"
                    )
                self.pos += 1
                continue
            out.append(char)
            self.pos += 1

    def number(self) -> int | float:
        match = _NUMBER_RE.match(self.text, self.pos)
        if match is None:
            self.fail("expected a number")
        self.pos = match.end()
        raw = match.group()
        return float(raw) if "." in raw else int(raw)

    def array(self) -> list[Any]:
        self.enter()
        self.pos += 1  # the '[', checked by the caller
        items: list[Any] = []
        self.skip_ws()
        if self.peek() == "]":
            self.pos += 1
            self.leave()
            return items
        while True:
            items.append(self.value())
            self.skip_ws()
            char = self.peek()
            if char == ",":
                self.pos += 1
                self.skip_ws()
                if self.peek() == "]":
                    self.fail("trailing comma before ']': remove it")
                continue
            if char == "]":
                self.pos += 1
                self.leave()
                return items
            if not char:
                self.fail(
                    "unclosed array: expected ',' or ']' before the end of the "
                    "declaration"
                )
            if char == ")":
                self.fail("unclosed array: expected ']' before the ')' that closes the call")
            self.missing_separator("',' or ']'", "]")

    def value(self) -> Any:
        """``string | number | array | ident | call``.

        An ``ident`` immediately followed by ``(`` is an inline component call, which is
        what "sub-components can be inline or referenced" means in the prompt their
        library generates. It is returned as a :class:`_Call` and flattened later.
        """
        self.skip_ws()
        char = self.peek()
        if not char:
            self.fail(
                "expected a value before the end of the declaration: text in double "
                "quotes, a number, an array or the id of another block"
            )
        if char == '"':
            value = self.string()
            self.last_value = "string"
            return value
        if char == "[":
            value = self.array()
            self.last_value = "array"
            return value
        if char == "-" or char.isdigit():
            value = self.number()
            self.last_value = "number"
            return value
        match = _IDENT_RE.match(self.text, self.pos)
        if match is None:
            self.fail(
                f"unexpected character {char!r}: a value is text in double quotes, a "
                "number, an array or the id of another block"
            )
        self.pos = match.end()
        after_ident = self.pos
        self.skip_ws()
        if self.peek() == "(":
            call = _Call(match.group(), self.args())
            self.last_value = "call"
            return call
        self.pos = after_ident  # so the next failure points at the offending character
        self.last_value = "ref"
        # Folded here and in ``_parse_line``, the only two places an id enters the
        # program, so a reference to ``conclusión`` and the declaration of ``conclusión``
        # land on the same ASCII name without either side knowing the other exists.
        folded = fold_identifier(match.group())
        if not folded:
            self.fail(
                f"the block id {match.group()!r} has no letters a-z in it: name the "
                "blocks with plain ASCII words, e.g. 'conclusion'"
            )
        return _Ref(folded)

    def args(self) -> list[Any]:
        self.expect_open()
        self.enter()
        items: list[Any] = []
        self.skip_ws()
        if self.peek() == ")":
            self.pos += 1
            self.leave()
            return items
        while True:
            items.append(self.value())
            self.skip_ws()
            char = self.peek()
            if char == ",":
                self.pos += 1
                continue
            if char == ")":
                self.pos += 1
                self.leave()
                return items
            if not char:
                self.fail(
                    "unclosed call: expected ',' or ')' before the end of the "
                    "declaration"
                )
            self.missing_separator("',' or ')'", ")")


#: Characters that can only start a *stray continuation*: a fragment left over after the
#: previous declaration already closed all its brackets. ``src/render/lines.py`` has
#: already absorbed every line that continues a declaration *properly* (one with a
#: bracket still open), so anything reaching this list is a genuine leftover — the model
#: closed the call and then kept writing arguments — and saying so is worth more than
#: repeating the grammar at it.
_CONTINUATION_STARTS = ')]},"'


def _parse_line(line: str, line_no: int) -> _Statement:
    """``ident "=" call`` → a :class:`_Statement` whose args may still hold ``_Call``s."""
    head = _LINE_RE.match(line)
    if head is None:
        stripped = line.lstrip()
        if stripped[:1] in _CONTINUATION_STARTS:
            message = (
                "this line continues a declaration that was already closed on the "
                "previous line: every declaration is one complete "
                "'id = Componente(argumentos)', and the arguments cannot be added "
                "after its ')'"
            )
        else:
            message = "expected a declaration of the form: id = Componente(argumentos)"
        raise RenderParseError(message, line_no=line_no, line=line)
    ident = fold_identifier(head.group(1))
    if not ident:
        raise RenderParseError(
            f"the block id {head.group(1)!r} has no letters a-z in it: name the blocks "
            "with plain ASCII words, e.g. 'conclusion'",
            line_no=line_no,
            line=line,
        )
    scanner = _Scanner(line, line_no, head.end())
    comp_name = scanner.comp_name()
    args = scanner.args()
    scanner.skip_ws()
    if not scanner.eof:
        scanner.fail(
            f"unexpected trailing text after ')': {line[scanner.pos :]!r}. One "
            "declaration per line, and nothing else on it"
        )
    return _Statement(ident, comp_name, args, line_no, line)


def _assert_closed(logical: LogicalLine) -> None:
    """A declaration whose brackets never closed, and which parsed anyway.

    Nearly unreachable, and deliberately kept: every route to it that has been found so
    far — an unterminated text value, a call that runs into the end of the program — is
    caught first by the scanner with a better message, so this is the net under the ones
    that have not been found.
    """
    if logical.closed:
        return
    raise RenderParseError(
        "this declaration opens a '(' or a '[' that is never closed: the program ends "
        "in the middle of it. Close every bracket before the end of the program",
        line_no=logical.line_no,
        line=logical.text,
    )


def _assert_no_fold_collision(statements: list[_Statement]) -> None:
    """Two ids that differ only by an accent are one id after the fold, and that is a bug.

    ``conclusión`` and ``conclusion`` in the same program both become ``conclusion``, and
    silently keeping the last one would drop a block the model meant to show. Rare enough
    that it has never been measured; named explicitly because the alternative — a
    duplicate-id error from ``UISpec``, whose message talks about a name the model never
    typed — is exactly the kind of message that makes the repair loop chase a ghost.
    """
    seen: dict[str, tuple[str, int]] = {}
    for statement in statements:
        head = _LINE_RE.match(statement.line)
        written = head.group(1) if head is not None else statement.ident
        previous = seen.get(statement.ident)
        if previous is None:
            seen[statement.ident] = (written, statement.line_no)
            continue
        if previous[0] == written:
            # The same name typed twice. Not a fold problem; ``UISpec`` reports it as the
            # duplicate id it is, using the name the model actually wrote.
            continue
        raise RenderParseError(
            f"the blocks {previous[0]!r} (line {previous[1]}) and {written!r} are the "
            f"same id {statement.ident!r} once the accents are removed: give them names "
            "that differ by more than an accent",
            line_no=statement.line_no,
            line=statement.line,
        )


def _spec_of(statement: _Statement) -> ComponentSpec:
    """The kit entry for a statement's component, or the closed-catalogue error."""
    spec: ComponentSpec | None = UI_KIT.get(statement.comp_name)
    if spec is None or (not spec.llm_emittable and not spec.legacy_parseable):
        raise RenderParseError(
            f"unknown component {statement.comp_name!r}; the catalogue is closed: "
            f"{', '.join(LLM_COMPONENT_NAMES)}",
            line_no=statement.line_no,
            line=statement.line,
        )
    if len(statement.args) != len(spec.props):
        raise RenderParseError(
            f"{statement.comp_name} takes {len(spec.props)} positional arguments — "
            f"{spec.signature} — got {len(statement.args)}",
            line_no=statement.line_no,
            line=statement.line,
        )
    return spec


def _holds_call(value: Any) -> bool:
    if isinstance(value, _Call):
        return True
    return isinstance(value, list) and any(_holds_call(item) for item in value)


def _expand(statement: _Statement, taken: set[str]) -> list[_Statement]:
    """Flatten the inline calls of one statement. Owner first, then what was nested in it.

    Ids are synthetic but **deterministic**: ``owner_1``, ``owner_2``, … in reading
    order, and ``owner_1_1`` for a call nested inside ``owner_1``. The same program has
    to produce the same ``UISpec`` every time it is parsed — the round trip, the cache
    key and ``node_render_views`` all compare specs across runs — so a counter is the
    whole scheme and nothing here may depend on a dict order or an object address. A
    candidate that an explicit declaration already claims is skipped, which is why
    ``taken`` carries every id in the program before the first expansion.

    Rule 4 (12 components, 5 children at the root) is checked by ``UISpec`` on the
    flattened list, so ten inline blocks cost exactly what ten declared ones cost.
    """
    spec = _spec_of(statement)
    produced: list[_Statement] = []
    index = 0

    def synthesize(call: _Call) -> _Ref:
        nonlocal index
        while True:
            index += 1
            candidate = f"{statement.ident}{_SYNTHETIC_SEP}{index}"
            if candidate not in taken:
                break
        taken.add(candidate)
        inner = _Statement(
            candidate, call.name, call.args, statement.line_no, statement.line
        )
        produced.extend(_expand(inner, taken))
        return _Ref(candidate)

    args: list[Any] = []
    for prop, value in zip(spec.props, statement.args, strict=True):
        if prop.kind is PropKind.REFS and isinstance(value, list):
            args.append(
                [synthesize(item) if isinstance(item, _Call) else item for item in value]
            )
            continue
        if prop.kind is not PropKind.REFS and _holds_call(value):
            raise RenderParseError(
                f"{statement.comp_name}: the argument {prop.signature} does not take a "
                "component. A component can only be nested inside a children array; "
                "elsewhere, declare it as 'id = Componente(...)' on its own line and "
                "pass the id",
                line_no=statement.line_no,
                line=statement.line,
            )
        # A ``ref[]`` prop that is not an array at all keeps its value: the message about
        # what a children array looks like belongs to ``_component_from_call``.
        args.append(value)

    return [statement._replace(args=args), *produced]


def _component_from_call(statement: _Statement) -> Component:
    """A flattened statement (no ``_Call`` left in ``args``) → a validated ``Component``."""
    spec = _spec_of(statement)

    props: dict[str, Any] = {}
    children: list[str] = []
    for prop, value in zip(spec.props, statement.args, strict=True):
        if prop.kind is PropKind.REFS:
            if not isinstance(value, list) or not all(isinstance(v, _Ref) for v in value):
                raise RenderParseError(
                    f"{statement.comp_name} argument {prop.name!r} must be an array of "
                    "component ids without quotes, e.g. [intro, steps], or of component "
                    'calls, e.g. [TextContent("Hola.", "lead")]',
                    line_no=statement.line_no,
                    line=statement.line,
                )
            children = [ref.name for ref in value]
        else:
            props[prop.name] = _unwrap(value)

    try:
        return Component(
            id=statement.ident, type=statement.comp_name, props=props, children=children
        )
    except PydanticValidationError as exc:
        raise RenderParseError(
            "; ".join(flatten_validation_error(exc)),
            line_no=statement.line_no,
            line=statement.line,
        ) from exc


def _unwrap(value: Any) -> Any:
    """Keep ``_Ref`` distinguishable so kit validation rejects it as a value."""
    if isinstance(value, _Ref):
        return {"$ref": value.name}
    if isinstance(value, list):
        return [_unwrap(item) for item in value]
    return value


def _pick_root(components: list[Component]) -> str:
    if not components:
        return ""
    referenced = {child for component in components for child in component.children}
    unreferenced = [c.id for c in components if c.id not in referenced]
    if len(unreferenced) == 1:
        return unreferenced[0]
    if any(c.id == "root" for c in components):
        return "root"
    if unreferenced:
        return unreferenced[0]
    return components[0].id


def infer_format(components: list[Component]) -> str:
    """Recover ``UISpec.format`` from the component mix.

    The dialect has no header line (the grammar is frozen at ``program = { line }``),
    so the format is either supplied by the caller or derived here. Deterministic and
    total, which is what makes the round trip exact.
    """
    types = {c.type for c in components}
    has_quiz = "QuizItem" in types
    content = types & _CONTENT_TYPES
    if has_quiz and content:
        return "mixed"
    if has_quiz:
        return "exercise"
    if "Chart" in types:
        return "chart"
    return "explanation"


def _quote(text: str) -> str:
    """The three escape rules, applied in the only safe order."""
    escaped = (
        text.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\r\n", "\\n")
        .replace("\r", "\\n")
        .replace("\n", "\\n")
    )
    return f'"{escaped}"'


def _number(value: Any) -> str:
    if isinstance(value, bool) or not isinstance(value, int | float):
        raise RenderError(f"{value!r} is not a number")
    return str(value)


def _render_value(value: Any, prop: PropSpec) -> str:
    match prop.kind:
        case PropKind.STRING | PropKind.ENUM:
            if not isinstance(value, str):
                raise RenderError(f"prop {prop.name!r} must be a string, got {value!r}")
            return _quote(value)
        case PropKind.STRING_LIST:
            if not isinstance(value, list):
                raise RenderError(f"prop {prop.name!r} must be an array, got {value!r}")
            return "[" + ", ".join(_quote(str(item)) for item in value) + "]"
        case PropKind.STRING_MATRIX:
            if not isinstance(value, list):
                raise RenderError(f"prop {prop.name!r} must be an array, got {value!r}")
            rows = [
                "[" + ", ".join(_quote(str(cell)) for cell in row) + "]" for row in value
            ]
            return "[" + ", ".join(rows) + "]"
        case PropKind.NUMBER_LIST:
            if not isinstance(value, list):
                raise RenderError(f"prop {prop.name!r} must be an array, got {value!r}")
            return "[" + ", ".join(_number(item) for item in value) + "]"
        case PropKind.REFS:  # pragma: no cover - handled by the caller
            raise RenderError("refs are serialized from Component.children")


class OpenUiLangBackend:
    """Reference implementation of :class:`~src.render.backends.base.RenderBackend`."""

    name = "openui"

    # -- parsing -------------------------------------------------------------------

    def parse(self, raw: str, *, ui_format: str | None = None) -> UISpec:
        """Parse a complete program. Raises ``RenderParseError``.

        Two passes, because the synthetic ids of the inline form must not be able to
        collide with an id the program declares three lines further down.
        """
        statements: list[_Statement] = []
        for logical in logical_lines(raw):
            # ``_parse_line`` first: an unclosed declaration almost always has a sharper
            # thing to say about itself (an unterminated text value, a call that reached
            # the end of the program mid-argument) than "a bracket is open", and the
            # sharper message is the one the repair loop can act on.
            statements.append(_parse_line(logical.text, logical.line_no))
            _assert_closed(logical)

        _assert_no_fold_collision(statements)

        taken = {statement.ident for statement in statements}
        components: list[Component] = [
            _component_from_call(flattened)
            for statement in statements
            for flattened in _expand(statement, taken)
        ]

        if not components:
            raise RenderParseError(
                "empty program: expected at least one 'id = Componente(...)' line"
            )

        return parse_spec(
            {
                "version": UI_SPEC_VERSION,
                "format": ui_format or infer_format(components),
                "root": _pick_root(components),
                "components": [c.model_dump() for c in components],
            }
        )

    def parse_partial(self, raw: str, *, ui_format: str | None = None) -> UISpec:
        """Tolerant parse of a stream prefix. Never raises.

        Drops the trailing line while it is still half-written, and silently skips any
        line that does not parse — mid-stream a truncated line is normal, not an error.
        A line whose inline nesting is only half-written is one of those: it is skipped
        whole, exactly as a half-written referenced line is, and reappears complete on
        the next chunk.

        ``taken`` can only hold the ids seen so far, so unlike :meth:`parse` a synthetic
        id may still be claimed by a declaration that has not streamed in yet. That is the
        same situation as a retransmitted line and it resolves the same way: the later
        declaration replaces the earlier component.
        """
        lines = logical_lines(raw)
        if lines and (not raw.endswith("\n") or not lines[-1].closed):
            # The tail is still being written, or it opened a bracket it never closed
            # (which mid-stream means the same thing). Both are dropped whole and
            # reappear complete on the next chunk.
            lines = lines[:-1]

        components: list[Component] = []
        index: dict[str, int] = {}
        taken: set[str] = set()
        for logical in lines:
            try:
                statement = _parse_line(logical.text, logical.line_no)
                taken.add(statement.ident)
                produced = [
                    _component_from_call(flattened)
                    for flattened in _expand(statement, taken)
                ]
            except (RenderError, PydanticValidationError, ValueError):
                continue
            for component in produced:
                if component.id in index:
                    components[index[component.id]] = component
                else:
                    index[component.id] = len(components)
                    components.append(component)

        payload = {
            "version": UI_SPEC_VERSION,
            "format": ui_format or infer_format(components),
            "root": _pick_root(components),
            "components": [c.model_dump() for c in components],
        }
        try:
            return parse_spec(payload, partial=True)
        except RenderError:
            # Cannot happen with the payload above; the contract is "never raises".
            return UISpec.model_construct(
                version=UI_SPEC_VERSION,
                format=str(payload["format"]),
                root=str(payload["root"]),
                components=components,
            )

    # -- serialization -------------------------------------------------------------

    def serialize(self, spec: UISpec) -> str:
        """Spec -> the canonical program text. The only thing the browser may receive.

        **One statement per component, children always as references, never inline.**
        ``parse`` accepts both forms; this writes the one their own prompt recommends
        ("prefer references for better streaming"), and it is what keeps ``serialize``
        the inverse of ``parse``: an inline program and its referenced form are the same
        ``UISpec``, so only one of them can be the canonical text, and the flat form is
        also the only one that gives the browser a real ``statementId`` per block. Round
        trip: ``parse(serialize(spec)) == spec``, and ``serialize(parse(inline))`` is a
        fixed point — reparsing it changes nothing, because the synthetic ids are by then
        ordinary declared ids.

        Covers the **whole** kit, ``Markdown`` included, which ``parse`` still refuses:
        the asymmetry is the point. The model may not emit ``Markdown``; the server
        authors it for ``fallback_seed``, and now that the browser is served dialect
        instead of JSON, the fallback needs a dialect form too. The frontend library
        therefore registers ten components while the prompt catalogue advertises nine.
        """
        lines: list[str] = []
        for component in spec.components:
            kit_spec = UI_KIT.get(component.type)
            if kit_spec is None:
                raise RenderError(f"component type {component.type!r} is not in the kit")
            args = [
                "[" + ", ".join(component.children) + "]"
                if prop.kind is PropKind.REFS
                else _render_value(component.props.get(prop.name), prop)
                for prop in kit_spec.props
            ]
            lines.append(f"{component.id} = {component.type}({', '.join(args)})")
        return "".join(f"{line}\n" for line in lines)


__all__ = ["MAX_NESTING_DEPTH", "OpenUiLangBackend", "infer_format"]
