"""Rich-media artifact pipeline (NotebookLM imitation).

The shared spine every media generator plugs into:

* :mod:`grounding` — assembles the cited source bundle a generator is fed.
* :mod:`assets` — stores generated bytes on disk, deduped by content hash.
* :mod:`images` — the image-generation utility (Gemini via OpenRouter, gpt-image-1 fallback).
* :mod:`jobs` — the async job runner and the ``MediaGenerator`` interface.
"""
