"""dynamic courses (v2): 13 tables, 8 enums, courses +6 columns, generation_step +2 values

Revision ID: 0005
Revises: 0004
Create Date: 2026-07-25

Hand-written (not autogenerated).

Creation order matters. Two forward references exist in the schema of §3:
``course_nodes.default_ui_format`` needs the ``ui_format`` type, and
``learner_node_states.active_render_id`` needs ``node_renders``. So: every
``CREATE TYPE`` first, then ``course_nodes`` -> ``course_node_prerequisites`` ->
``node_renders`` -> ``learner_node_states`` -> the rest -> ``node_render_views``.

**No ``op.execute("COMMIT")`` here, deliberately.** The deployment target is pg16
(``pgvector/pgvector:pg16``) where ``ALTER TYPE ... ADD VALUE`` works inside a
transaction; only *using* the new value in the same transaction is forbidden, and
this migration never does. Meanwhile ``alembic/env.py`` wraps the whole run in one
``context.begin_transaction()`` (no ``transaction_per_migration``) and
``src/main.py`` runs migrations in the lifespan — a mid-run COMMIT would confirm
0001..0004 and leave startup in a partial state if 0005 then failed.

``downgrade()`` scope, stated honestly: it drops the 13 new tables, the 6 new
``courses`` columns and the 8 new enums, but **leaves ``schema_proposing`` and
``schema_proposed`` orphaned in the ``generation_step`` type**. PostgreSQL cannot
remove a value from an enum; a truly clean downgrade would mean recreating the
type and rewriting ``generation_jobs.status``. That is not done, and this comment
is the documented reason. ``tests/integration/test_migration_0005.py`` asserts
exactly that shape.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# --- The 8 new enum types (§3.6) ---
NEW_ENUMS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("course_delivery_mode", ("static", "dynamic")),
    ("course_schema_status", ("draft", "proposed", "validated", "archived")),
    ("node_criticality", ("critical", "recommended", "contextual")),
    ("learner_experience", ("unknown", "none", "some", "experienced")),
    ("node_state", ("not_started", "probing", "learning", "mastered", "needs_review")),
    ("error_kind", ("detail", "procedural", "conceptual")),
    ("ui_format", ("explanation", "simulation", "exercise", "chart", "mixed")),
    (
        "node_render_status",
        ("pending", "generating", "ready", "failed", "fallback"),
    ),
)

# Reverse creation order, for downgrade.
NEW_TABLES: tuple[str, ...] = (
    "course_nodes",
    "course_node_prerequisites",
    "node_renders",
    "learner_node_states",
    "learner_profiles",
    "learning_events",
    "node_probes",
    "node_attempts",
    "node_feedback",
    "term_explanations",
    "llm_usage_log",
    "audit_log",
    "node_render_views",
)

COURSES_NEW_COLUMNS: tuple[str, ...] = (
    "delivery_mode",
    "schema_status",
    "schema_validated_by",
    "schema_validated_at",
    "schema_version",
    "intent_density",
)


def _enum(name: str) -> postgresql.ENUM:
    """Reference an already-created type; never re-emits CREATE TYPE."""
    values = dict(NEW_ENUMS)[name]
    return postgresql.ENUM(*values, name=name, create_type=False)


def upgrade() -> None:
    bind = op.get_bind()

    # ── 1. Every CREATE TYPE first ──────────────────────────────
    for name, values in NEW_ENUMS:
        postgresql.ENUM(*values, name=name).create(bind, checkfirst=True)

    # The design-time 'schema' step of the generation pipeline. Safe inside the
    # surrounding transaction on pg12+; the values are not used until 0005 is done.
    op.execute(
        "ALTER TYPE generation_step ADD VALUE IF NOT EXISTS 'schema_proposing' "
        "BEFORE 'extracting'"
    )
    op.execute(
        "ALTER TYPE generation_step ADD VALUE IF NOT EXISTS 'schema_proposed' "
        "AFTER 'reviewing'"
    )

    # ── 2. courses: 6 additive columns, all defaulted ───────────
    op.add_column(
        "courses",
        sa.Column(
            "delivery_mode",
            _enum("course_delivery_mode"),
            nullable=False,
            server_default="static",
        ),
    )
    op.add_column(
        "courses",
        sa.Column(
            "schema_status",
            _enum("course_schema_status"),
            nullable=False,
            server_default="draft",
        ),
    )
    op.add_column("courses", sa.Column("schema_validated_by", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        "fk_courses_schema_validated_by",
        "courses",
        "users",
        ["schema_validated_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "courses",
        sa.Column("schema_validated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "courses",
        sa.Column(
            "schema_version", sa.Integer(), nullable=False, server_default=sa.text("1")
        ),
    )
    op.add_column(
        "courses",
        sa.Column(
            "intent_density",
            sa.SmallInteger(),
            nullable=False,
            server_default=sa.text("3"),
        ),
    )
    op.create_check_constraint(
        "ck_courses_intent_density", "courses", "intent_density BETWEEN 1 AND 5"
    )

    # ── 3. course_nodes ─────────────────────────────────────────
    op.create_table(
        "course_nodes",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sa.Uuid(), nullable=True),
        sa.Column("seed_lesson_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("outcome", sa.Text(), nullable=True),
        sa.Column(
            "criticality",
            _enum("node_criticality"),
            nullable=False,
            server_default="recommended",
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("source_document_id", sa.Uuid(), nullable=True),
        sa.Column(
            "source_headings",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::text[]"),
        ),
        sa.Column(
            "mastery_threshold",
            sa.REAL(),
            nullable=False,
            server_default=sa.text("0.80"),
        ),
        sa.Column(
            "default_ui_format",
            _enum("ui_format"),
            nullable=False,
            server_default="explanation",
        ),
        sa.Column(
            "probe_items",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column(
            "probe_answer_key",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column("estimated_minutes", sa.Integer(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column(
            "archived", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["seed_lesson_id"], ["lessons.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"], ["documents.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["reviewed_by"], ["users.id"], ondelete="SET NULL"),
        sa.CheckConstraint(
            "mastery_threshold > 0 AND mastery_threshold <= 1",
            name="ck_course_nodes_mastery_threshold",
        ),
        # DEFERRABLE so PUT /courses/{id}/schema can swap two positions in one
        # statement batch after SET CONSTRAINTS ... DEFERRED.
        sa.UniqueConstraint(
            "course_id",
            "position",
            name="uq_course_nodes_position",
            deferrable=True,
            initially="IMMEDIATE",
        ),
    )
    op.create_index("idx_course_nodes_course", "course_nodes", ["course_id", "position"])
    op.create_index("idx_course_nodes_skill", "course_nodes", ["skill_id"])

    # ── 4. course_node_prerequisites ────────────────────────────
    op.create_table(
        "course_node_prerequisites",
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("prerequisite_node_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint(
            "node_id", "prerequisite_node_id", name="pk_course_node_prerequisites"
        ),
        sa.ForeignKeyConstraint(["node_id"], ["course_nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["prerequisite_node_id"], ["course_nodes.id"], ondelete="CASCADE"
        ),
        sa.CheckConstraint(
            "node_id <> prerequisite_node_id", name="ck_node_prereq_not_self"
        ),
    )
    op.create_index("idx_node_prereq_node", "course_node_prerequisites", ["node_id"])

    # ── 5. node_renders (no user_id — the row is shared) ────────
    op.create_table(
        "node_renders",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("generated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "is_preview", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("cache_key", sa.Text(), nullable=False),
        sa.Column("ui_format", _enum("ui_format"), nullable=False),
        sa.Column(
            "ui_spec",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "answer_key",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column("raw_dsl", sa.Text(), nullable=True),
        sa.Column("backend", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("tier", sa.Text(), nullable=False),
        sa.Column(
            "status",
            _enum("node_render_status"),
            nullable=False,
            server_default="pending",
        ),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["generated_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["node_id"], ["course_nodes.id"], ondelete="CASCADE"),
        sa.CheckConstraint("tier IN ('fast', 'heavy')", name="ck_node_renders_tier"),
        sa.UniqueConstraint("cache_key", name="uq_node_renders_cache_key"),
    )
    op.create_index(
        "idx_node_renders_node",
        "node_renders",
        ["node_id", sa.text("created_at DESC")],
    )
    op.create_index("idx_node_renders_status", "node_renders", ["status"])

    # ── 6. learner_node_states (needs node_renders) ─────────────
    op.create_table(
        "learner_node_states",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column(
            "state", _enum("node_state"), nullable=False, server_default="not_started"
        ),
        sa.Column("mastery", sa.REAL(), nullable=False, server_default=sa.text("0")),
        sa.Column("probe_score", sa.REAL(), nullable=True),
        sa.Column(
            "consecutive_correct",
            sa.SmallInteger(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "consecutive_failed",
            sa.SmallInteger(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "hints_used", sa.SmallInteger(), nullable=False, server_default=sa.text("0")
        ),
        sa.Column(
            "attempts_count", sa.Integer(), nullable=False, server_default=sa.text("0")
        ),
        sa.Column("last_error_kind", _enum("error_kind"), nullable=True),
        sa.Column("active_render_id", sa.Uuid(), nullable=True),
        sa.Column(
            "render_pinned", sa.Boolean(), nullable=False, server_default=sa.text("true")
        ),
        sa.Column(
            "scaffold_band", sa.Text(), nullable=False, server_default="neutral"
        ),
        sa.Column("waived_by", sa.Uuid(), nullable=True),
        sa.Column("waived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mastered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["node_id"], ["course_nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["active_render_id"], ["node_renders.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["waived_by"], ["users.id"], ondelete="SET NULL"),
        sa.CheckConstraint("mastery >= 0 AND mastery <= 1", name="ck_lns_mastery"),
        sa.CheckConstraint(
            "probe_score IS NULL OR (probe_score >= 0 AND probe_score <= 1)",
            name="ck_lns_probe_score",
        ),
        sa.CheckConstraint(
            "scaffold_band IN ('novice','neutral','advanced')",
            name="ck_lns_scaffold_band",
        ),
        sa.UniqueConstraint("user_id", "node_id", name="uq_lns_user_node"),
    )
    op.create_index("idx_lns_user", "learner_node_states", ["user_id"])
    op.create_index("idx_lns_state", "learner_node_states", ["user_id", "state"])

    # ── 7. learner_profiles ─────────────────────────────────────
    op.create_table(
        "learner_profiles",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_title", sa.Text(), nullable=True),
        sa.Column("sector", sa.Text(), nullable=True),
        sa.Column("goal", sa.Text(), nullable=True),
        sa.Column(
            "experience_level",
            _enum("learner_experience"),
            nullable=False,
            server_default="unknown",
        ),
        # Reuses the existing learning_profile enum; no new type.
        sa.Column(
            "preset",
            postgresql.ENUM(
                "standard", "focus", "fast", name="learning_profile", create_type=False
            ),
            nullable=False,
            server_default="standard",
        ),
        sa.Column(
            "format_vector",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text(
                """'{"texto":0,"ejercicio":0,"codigo":0,"dato":0}'::jsonb"""
            ),
        ),
        sa.Column(
            "format_vector_updated_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "nodes_completed", sa.Integer(), nullable=False, server_default=sa.text("0")
        ),
        sa.Column(
            "tutor_notes",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "onboarding_completed_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "onboarding_skipped",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        sa.Column(
            "onboarding_version",
            sa.SmallInteger(),
            nullable=False,
            server_default=sa.text("1"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.UniqueConstraint("user_id", name="uq_learner_profiles_user"),
    )

    # ── 8. learning_events ──────────────────────────────────────
    op.create_table(
        "learning_events",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=True),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("element", sa.Text(), nullable=True),
        sa.Column("weight", sa.REAL(), nullable=False, server_default=sa.text("0")),
        sa.Column(
            "metadata",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["node_id"], ["course_nodes.id"], ondelete="SET NULL"),
    )
    op.create_index(
        "idx_learning_events_user",
        "learning_events",
        ["user_id", sa.text("created_at DESC")],
    )

    # ── 9. node_probes ──────────────────────────────────────────
    op.create_table(
        "node_probes",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column(
            "attempt_no", sa.SmallInteger(), nullable=False, server_default=sa.text("1")
        ),
        sa.Column("items", postgresql.JSONB(), nullable=False),
        sa.Column(
            "answer_key",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "answers",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column("score", sa.REAL(), nullable=True),
        sa.Column("mastered", sa.Boolean(), nullable=True),
        sa.Column(
            "tiebreak_used",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        sa.Column(
            "scored", sa.Boolean(), nullable=False, server_default=sa.text("true")
        ),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["node_id"], ["course_nodes.id"], ondelete="CASCADE"),
        sa.CheckConstraint(
            "score IS NULL OR (score >= 0 AND score <= 1)", name="ck_node_probes_score"
        ),
    )
    # The anti-retry rule: one scored probe per (user, node, schema_version).
    op.create_index(
        "uq_node_probes_user_node_version",
        "node_probes",
        ["user_id", "node_id", "schema_version"],
        unique=True,
        postgresql_where=sa.text("scored"),
    )
    op.create_index(
        "idx_node_probes_user_node",
        "node_probes",
        ["user_id", "node_id", sa.text("created_at DESC")],
    )

    # ── 10. node_attempts ───────────────────────────────────────
    op.create_table(
        "node_attempts",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("render_id", sa.Uuid(), nullable=True),
        sa.Column("probe_id", sa.Uuid(), nullable=True),
        sa.Column("item_id", sa.Text(), nullable=False),
        # Reuses the existing exercise_type enum; no new type.
        sa.Column(
            "item_type",
            postgresql.ENUM(
                "test",
                "true_false",
                "fill_blank",
                "order_steps",
                "practical_case",
                "dialogue",
                name="exercise_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("bloom_level", sa.Text(), nullable=True),
        sa.Column("answer", postgresql.JSONB(), nullable=False),
        sa.Column("score", sa.REAL(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column(
            "hints_used", sa.SmallInteger(), nullable=False, server_default=sa.text("0")
        ),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "attempted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["node_id"], ["course_nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["render_id"], ["node_renders.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["probe_id"], ["node_probes.id"], ondelete="SET NULL"),
        sa.CheckConstraint(
            "bloom_level IN ('remember','understand','apply','analyze','evaluate','create')",
            name="ck_node_attempts_bloom_level",
        ),
        sa.CheckConstraint("score >= 0 AND score <= 1", name="ck_node_attempts_score"),
    )
    op.create_index(
        "idx_node_attempts_user_node",
        "node_attempts",
        ["user_id", "node_id", sa.text("attempted_at DESC")],
    )

    # ── 11. node_feedback ───────────────────────────────────────
    op.create_table(
        "node_feedback",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("difficulty", sa.Text(), nullable=False),
        sa.Column("unclear", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["node_id"], ["course_nodes.id"], ondelete="CASCADE"),
        sa.CheckConstraint(
            "difficulty IN ('easy', 'ok', 'hard')", name="ck_node_feedback_difficulty"
        ),
        sa.UniqueConstraint("user_id", "node_id", name="uq_node_feedback_user_node"),
    )

    # ── 12. term_explanations ───────────────────────────────────
    op.create_table(
        "term_explanations",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=True),
        sa.Column("term", sa.Text(), nullable=False),
        sa.Column("term_normalized", sa.Text(), nullable=False),
        sa.Column("context_hash", sa.Text(), nullable=False),
        sa.Column("language", sa.Text(), nullable=False, server_default="es"),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column(
            "hit_count", sa.Integer(), nullable=False, server_default=sa.text("0")
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_used_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["node_id"], ["course_nodes.id"], ondelete="SET NULL"),
        sa.UniqueConstraint(
            "org_id",
            "term_normalized",
            "context_hash",
            "language",
            name="uq_term_explanations_lookup",
        ),
    )
    op.create_index(
        "idx_term_expl_lookup",
        "term_explanations",
        ["org_id", "term_normalized", "context_hash"],
    )
    op.create_index("idx_term_expl_purge", "term_explanations", ["last_used_at"])

    # ── 13. llm_usage_log ───────────────────────────────────────
    op.create_table(
        "llm_usage_log",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("use_case", sa.Text(), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("tier", sa.Text(), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("ok", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.CheckConstraint(
            "tier IS NULL OR tier IN ('fast','heavy')", name="ck_llm_usage_log_tier"
        ),
    )
    op.create_index(
        "idx_llm_usage_case",
        "llm_usage_log",
        ["org_id", "use_case", sa.text("created_at DESC")],
    )

    # ── 14. audit_log ───────────────────────────────────────────
    op.create_table(
        "audit_log",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column(
            "detail",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
    )
    op.create_index(
        "idx_audit_log_subject",
        "audit_log",
        ["org_id", "subject", sa.text("created_at DESC")],
    )

    # ── 15. node_render_views (references node_renders + course_nodes) ──
    op.create_table(
        "node_render_views",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("render_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id", "render_id", name="pk_node_render_views"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["render_id"], ["node_renders.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["node_id"], ["course_nodes.id"], ondelete="CASCADE"),
    )
    op.create_index(
        "idx_node_render_views_user",
        "node_render_views",
        ["user_id", "node_id", sa.text("first_seen_at DESC")],
    )

    # ── 16. generation_jobs: at most one schema job in flight per course ──
    # The concurrency half of the idempotency guard in
    # ``CourseSchemaService.propose``. The read there closes the double-click case;
    # this closes the race, where two requests both find nothing and both insert.
    # Partial on purpose: it constrains only rows that are *running a schema
    # proposal*, so the v1 content pipeline (extracting/structuring/generating over
    # the same ``result_course_id``) is untouched, and a finished, failed or
    # cancelled schema job never blocks the next proposal.
    op.execute(
        "CREATE UNIQUE INDEX uq_generation_jobs_schema_in_flight "
        "ON generation_jobs (result_course_id) "
        "WHERE status = 'schema_proposing' "
        "AND cancelled_at IS NULL "
        "AND result_course_id IS NOT NULL"
    )


def downgrade() -> None:
    bind = op.get_bind()

    # Not covered by the table drops below: generation_jobs predates this migration.
    op.execute("DROP INDEX IF EXISTS uq_generation_jobs_schema_in_flight")

    # Tables in reverse dependency order. Indexes go with the table.
    for table in reversed(NEW_TABLES):
        op.drop_table(table)

    # courses: drop the check first, then the 6 columns (the FK goes with its column).
    op.drop_constraint("ck_courses_intent_density", "courses", type_="check")
    for column in reversed(COURSES_NEW_COLUMNS):
        op.drop_column("courses", column)

    # The 8 new enum types.
    for name, values in reversed(NEW_ENUMS):
        postgresql.ENUM(*values, name=name).drop(bind, checkfirst=True)

    # DELIBERATELY NOT REVERSED: 'schema_proposing' and 'schema_proposed' stay in
    # generation_step. PostgreSQL cannot drop an enum value, and recreating the type
    # would mean rewriting generation_jobs.status. Harmless: no row references them
    # once the new tables are gone, and generation_service falls back to a known
    # value if one somehow survived. See the module docstring.
